# Introduction {#intro}

A U.S. American veterans organization regularly conducts direct marketing campaigns, asking their members for donations (gifts) for the treatment of veterans with spinal injuries. The goal for the organisation is to maximize the net profit from their campaigns.

Only a small proportion of the members give a gift in reply to a campaign, while each letter sent out has a unit cost of 0.68 $US. In order to maximize profit, it is therefore desirable to only mail members who are likely to donate.

The members are grouped, among other criteria, by the recency of their last gift. Of these groups, the so-called *lapsed* donors are of particular interest. These are members who made their last gift to the organisation 13 to 24 months prior to a given campaign.
This group is important for two reasons: Firstly, the likelihood of a member donating decreases with the time the member has not donated. Enticing these lapsed donors to give again therefore maintains an active member base. Secondly, the organisation has found that there is a negative correlation between the dollar amount donated and the likelihood to respond to a campaign. This means it is important to include the most unlikely donors in future mailings because if they donate, the net revenue is particularly large. If these unlikely donors would be suppressed from future campaigns, the gains from additional *small dollar* lapsed donors would not offset the losses from the potential *high dollar* donors.

The data at hand was distributed for the purpose of the KDD-CUP of the year 1998^[For an archive of past cups, see [SIGKDD - KDD Cup](http://www.kdd.org/kdd-cup)]. The cup was until recently held yearly under the aegis of the special interest group on Knowledge Discovery and Data Mining (SIGKDD), which itself is part of the Association for Computing Machinery^[https://acm.org] (ACM).

At the time of the competition, 20 years ago, machine learning was in it's second boom phase. Since then, there was one more period of slump before the current boom that started in the mid-2000's (see @Goodfellow-et-al-2016). Both computing power and tools available have undergone a substantial transformation since 1998, when the frontrunners in the KDD-CUP competition were all big players in the field, showcasing their proprietary software. This thesis thus also demonstrates the possibilities that are currently at hand, from powerful open-source toolkits like scikit-learn to cloud computing.



## Task

The task for this thesis was to perform a complete data analysis (data preprocessing, model evaluation, model selction, prediction).

A requirement set by the supervisor of this thesis was that the solution be demonstrated using Python (see @CS-R9526) as a programming environment.



## Goal

The ultimate goal was to beat the winner of the original cup in terms of the predicted net revenue for the campaign.

Furthermore, the thesis should support future work on the data set by providing a solid basis especially on the preprocessing of the data.

For reference, the exact problem description from the cup announcement is given in verbatim:

> [...], the objective of the analysis will be to maximize the net revenue generated from this mailing -- a censored regression or estimation problem. The response variable is, thus, continuous (for the lack of a better common term.) Although we are releasing both the binary and the continuous versions of the target variable (TARGET_B and TARGET_D respectively), the program committee will use the predicted value of the donation (dollar) amount (for the target variable TARGET_D) in evaluating the results. So, returning the predicted value of the binary target variable TARGET_B and its associated probability/strength will not be sufficient.
> The typical outcome of predictive modeling in database marketing is an estimate of the expected response/return per customer in the database. A marketer will mail to a customer so long as the expected return from an order exceeds the cost invested in generating the order, i.e., the cost of promotion. For our purpose, the package cost (including the mail cost) is $0.68 per piece mailed.
> KDD-CUP committee will evaluate the results based solely on the net revenue generated on the hold-out or validation sample.
> The measure we will use is: Sum (the actual donation amount - $0.68) over all records for which the expected revenue (or predicted value of the donation) is over $0.68.
> This is a direct measure of profit. The winner will be the participant with the highest actual sum. The results will be rounded to the nearest 10 dollars. 


## Glossary

In the scope of this thesis, the following naming conventions are used.

```{r glossary-table, results='asis', echo=F, cache=F}

tibble(
    Term = c("Example",
             "Feature",
             "Target",
             "Regularization",
             "Hyperparameter",
             "Generalization Error",
             "Promotion",
             "Gift"),
    Explanation = c("One observation of the data, a row in the matrix.",
          "One variable like *address*, *age* or *time since failure*, a column in the matrix",
          "The solution, or target variable, in the learning dataset. Used in supervised learning to train the algorithm.",
          "Constraints on the learning algorithm defined by *hyperparameters*. These parameters are of the learning algorithm, not the resulting model.",
          "A parameter controlling the learning algorithm. Generally, large (regularization) hyperparameters almost guarantee not overfitting the model at the cost of good performance.",
          "Also called out-of-sample error. The error rate on new observations.",
          "A solicitation to a member of the veterans organisation asking for a donation",
          "A donation made by a member to the veterans organisation")) %>% 
    arrange(Term) %>%
    kable(col.names = c('', ''),
             booktabs = T,
             caption = "Naming conventions.") %>%
    kable_styling(latex_options=c("hold_position", position="center")) %>%
    column_spec(1, width="3cm", bold=T) %>%
    column_spec(2, width="10cm")
```
