# (APPENDIX) Appendix {-} 

# Software

## Python Environment

Python was installed through the Anaconda distribution^[Available from [https://www.anaconda.com](https://www.anaconda.com)].

The analysis documented should be reproduced using the same environment, thereby ensuring that the packages produce the same results and expose the API's used in the code.

The environment can be created using the file `environment.yml` in the main repository directory at `r make_github_link()`.

Once conda is installed the following two commands first set up the environment with all the analysis' required packages, then activates that environment. Only after running these commands should the package `kdd98` be installed and the notebooks evaluated.

```
> conda env create -f environment.yml
> source activate msc-thesis-fh
```

## Package kdd98

The source code is at: `r make_github_link("kdd98")`

### Usage

#### Data Provisioning

```
from kdd98 import data_handler as dh

provider = dh.KDD98DataProvider(["cup98LRN.txt", "cup98VAL.txt"])

# Get data at several intermediate steps as necessary
provider.raw_data
provider.preprocessed_data
provider.numeric_data
provider.imputed_data
provider.all_relevant_data
```

By requesting `all_relevant_data`, all transformation steps are applied.
Request data for cup98LRN.txt first to learn all transformers involved.
Only then can the provider be instantiated with cup98VAL.txt and the exact same transformations applied to that data set.

#### Predictions

```
from kdd98.prediction import Kdd98ProfitEstimator

# These are found beforehand and expected to implement scikit-learn's API
classifier = SomeClassifier() # predicts donation probability
regressor = SomeRegressor() # conditionally predicts donation amount

estimator = Kdd98ProfitEstimator(classifier, regressor)

estimator.fit(X_learn, y_learn)

# Returns a tuple (indicator, net_profit):
estimator.predict(X_test, y_test)
```

### Installation

Clone the repository, then, from the base directory:

```
cd code

python setup.py install # for direct install

# for a conda package to be installed manually afterards:
python setup.py bdist_conda 
```

#### Project structure

After installing the package, several folders and files are created in the working directory when using it:

* ``data`` contains the data files and documentation of the original KDD Cup 1998
* ``data/data_frames`` contains pickled pandas df's with data at the corresponding transformation step
* ``models/internal`` contains persisted transformers for data set transformations.
* ``out.log`` reports transformation progress / potential problems


# KDD Cup Documents

## Cup Documentation {#data-set-documentation}

```
======================================================================
EPSILON CONFIDENTIAL      EPSILON CONFIDENTIAL    EPSILON CONFIDENTIAL

    INFORMATION LISTED BELOW IS AVAILABLE UNDER THE TERMS OF THE  
                      CONFIDENTIALITY AGREEMENT                

EPSILON CONFIDENTIAL      EPSILON CONFIDENTIAL    EPSILON CONFIDENTIAL
======================================================================

+--------------------------------------------------------------------+
|                   DOCUMENTATION TO ACCOMPANY                       |
|                                                                    |
|                          KDD-CUP-98                                |
|                                                                    |
|          The Second International Knowledge Discovery and          |
|                 Data Mining Tools Competition                      |
|                                                                    |
|                Held in Conjunction with KDD-98                     |
|                                                                    |
|          The Fourth International Conference on Knowledge          |
|                   Discovery and Data Mining                        |
|                    [www.kdnuggets.com] or                          |
|                 [www-aig.jpl.nasa.gov/kdd98] or                    |
|                [www.aaai.org/Conferences/KDD/1998]                 |
|                                                                    |
|                       Sponsored by the                             |
|                                                                    |
|      American Association for Artificial Intelligence (AAAI)       |
|                  Epsilon Data Mining Laboratory                    |
|                Paralyzed Veterans of America (PVA)                 |
+--------------------------------------------------------------------+
|                                                                    |
| Created:     7/20/98                                               |
| Last update: 7/22/98                                               |
| File name:   cup98DOC.txt                                          |
|                                                                    |
+--------------------------------------------------------------------+

Table of Contents:       

o IMPORTANT DATES (UPDATED)
o GENERAL INSTRUCTIONS (for DOWNLOADS, RESULT RETURNS, etc.)
o LISTING of the FILES (Contents of the README FILE)
o PROJECT OVERVIEW: A FUND RAISING NET RETURN PREDICTION MODEL
o EVALUATION RULES 
o DATA SOURCES and ORDER & TYPE OF THE VARIABLES IN THE DATA SETS 
o SUMMARY STATISTICS (MIN & MAX)
o DATA (PRE)PROCESSING
o KDD-CUP-98 PROGRAM COMMITTEE
o TERMINOLOGY-GLOSSARY


+--------------------------------------------------------------------+
| IMPORTANT DATES (UPDATED)                                          |
+--------------------------------------------------------------------+

o Release of the datasets, related documentation and the KDD-CUP
  questionnaire

  July 22, 1998

o Return of the results and the KDD-CUP questionnaire  

  August 19, 1998

o KDD-CUP Committee evaluation of the results

  August 19-25

o Individual performance evaluations send to the participants

  August 26, 1998
 
o Public announcement of the winners and awards presentation during
  KDD-98 in New York City

  August 29, 1998 


+--------------------------------------------------------------------+
| GENERAL INSTRUCTIONS (for DOWNLOADS, RESULT RETURNS, etc.)         | 
+--------------------------------------------------------------------+

1. FTP to 159.127.66.10. Login anonymous. Enter email ID as password.

3. The README file contains information about the files included in
the FTP server.  All data files are compressed. The files with .zip
extension are compressed with the PKZIP compression utility and they
are for participants with IBM PC compatible hardware. The PKUNZIP
utility is needed to unzip these files. The files with .Z extension
are UNIX COMPRESSed and they are for the participants with UNIX
compatible hardware. YOU WILL EITHER NEED THE DATA FILES <cup98LRN.ZIP
AND cup98VAL.ZIP> *OR* <cup98LRN.TXT.Z AND cup98VAL.TXT.Z>, BUT NOT
BOTH. REMEMBER TO FTP THESE FILES IN BINARY MODE.

4. The data sets are in comma delimited format. The learning dataset
<cup98LRN.txt> contains 95412 records and 481 fields. The first/header
row of the data set contains the field names.

The validation dataset <cup98VAL.txt> contains 96367 records and 479
variables. The first/header row of the data set contains the field
names.

THE RECORDS IN THE VALIDATION DATASET ARE IDENTICAL TO THE RECORDS IN
THE LEARNING DATASET EXCEPT THAT THE VALUES FOR THE TARGET/DEPENDENT
VARIABLES ARE MISSING (i.e., the fields TARGET_B and TARGET_D are
not included in the validation data set.)

5. The data dictionary (for both the learning and the validation data
set) is included in the file <cup98DIC.txt>. The fields in the data
dictionary are ordered by the position of the fields in the learning
data set. The dictionary for the validation data set is identical to
the dictionary for the learning data set except the two target fields
(target_B and target_D) are missing in the validation data set.

6. Blanks in the string (or character) variables/fields and periods in
the numeric variables correspond to missing values.

7. Each record has a unique record identifier or index (field name:
CONTROLN.) For each record, there are two target/dependent variables
(field names: TARGET_B and TARGET_D). TARGET_B is a binary variable
indicating whether or not the record responded to the promotion of
interest ("97NK" mailing) while TARGET_D contains the donation amount
(dollar) and is only observed for those that responded to the
promotion.

8. THE DEADLINE HAS BEEN EXTENDED. You are required to return the
questionnaire and the validation dataset of 96367 records by email to
<iparsa@epsilon.com> by AUGUST 19, 1998.

Each record in the returned file should consist of the following two
values:

a. The unique record identifier or index (field name: CONTROLN)
b. Predicted value of the donation (dollar) amount (for the target
variable TARGET_D) for that record 

You are also required to fill out the questionnaire (file name:
<cup98QUE.txt>. The questionnaire is used to summarize in bullet
points the data analytic techniques you've applied to the dataset.

9. Please send email to <iparsa@epsilon.com> when you download the
files so we can keep you informed about anything necessary.

10. Under no circumstances should any participant contact Paralyzed
Veterans of America (PVA) for any reason.

If you have any questions, please send email to <iparsa@epsilon.com.>

+--------------------------------------------------------------------+
| FILES LISTING (README FILE)                                        |
+--------------------------------------------------------------------+

File Naming Conventions: 

o cup98         : KDD-CUP-98 
o      QUE      : QUEstionnaire 
o      DOC      : DOCumentation
o      DIC      : DICtionary
o      LRN      : LeaRNing data set 
o      VAL      : VALidation data set 
o         .txt  : plain ascii text files
o         .zip  : PKZIP compressed files
o         .txt.Z: UNIX COMPRESSED files

FILE NAME       DESCRIPTION
--------------- ------------------------------------------------------

README          This list, listing the files in the FTP server and 
                their contents.

cup98NDA.txt    The Non-Disclosure Agreement. MUST BE SIGNED BY ALL 
                PARTICIPANTS AND MAILED BACK TO ISMAIL PARSA 
                <iparsa@epsilon.com> BEFORE DOWNLOADING THE DATA SETS.

cup98DOC.txt    This file, an overview and pointer to more detailed 
                information about the competition

cup98DIC.txt    Data dictionary to accompany the analysis data set. 

cup98QUE.txt    KDD-CUP questionnaire. PARTICIPANTS ARE REQUIRED TO
                FILL-OUT THE QUESTIONNAIRE and turned in
                with the results. 

cup98LRN.zip    PKZIP compressed raw LEARNING data set. 
                Internal name: cup98LRN.txt 
                File size: 36,468,735 bytes zipped. 117,167,952 bytes 
                unzipped.
                Number of Records: 95412.
                Number of Fields: 481.

cup98VAL.zip    PKZIP compressed raw VALIDATION data set. 
                Internal name: cup98VAL.txt 
                File size: 36,763,018 bytes zipped. 117,943,347 bytes 
                unzipped.
                Number of Records: 96367.
                Number of Fields: 479.
 
cup98LRN.txt.Z  UNIX COMPRESSed raw LEARNING data set. 
                Internal name: cup98LRN.txt 
                File size: 36,579,127 bytes compressed. 117,167,952 
                bytes uncompressed.
                Number of Records: 95412.
                Number of Fields: 481.

cup98VAL.txt.Z  UNIX COMPRESSed raw VALIDATION data set. 
                Internal name: cup98VAL.txt 
                File size: 36,903,761 bytes compressed. 117,943,347 
                bytes uncompressed.
                Number of Records: 96367.
                Number of Fields: 479.


+--------------------------------------------------------------------+
| PROJECT OVERVIEW: A Fund Raising Net Return Prediction Model       | 
+--------------------------------------------------------------------+

BACKGROUND AND OBJECTIVES
-------------------------

The data set for this year's Cup has been generously provided by the
Paralyzed Veterans of America (PVA).  PVA is a not-for-profit
organization that provides programs and services for US veterans with
spinal cord injuries or disease.  With an in-house database of over 13
million donors, PVA is also one of the largest direct mail fund
raisers in the country.

Participants in the '98 CUP will demonstrate the performance of their
tool by analyzing the results of one of PVA's recent fund raising
appeals.  This mailing was sent to a total of 3.5 million PVA donors
who were on the PVA database as of June 1997.  Everyone included in
this mailing had made at least one prior donation to PVA.

The mailing included a gift (or "premium") of personalized name &
address labels plus an assortment of 10 note cards and envelopes.  All
of the donors who received this mailing were acquired by PVA through
similar premium-oriented appeals such as this.

One group that is of particular interest to PVA is "Lapsed" donors.
These are individuals who made their last donation to PVA 13 to 24
months ago.  They represent an important group to PVA, since the
longer someone goes without donating, the less likely they will be to
give again.  Therefore, recapture of these former donors is a critical
aspect of PVA's fund raising efforts.

However, PVA has found that there is often an inverse correlation
between likelihood to respond and the dollar amount of the gift, so a
straight response model (a classification or discrimination task) will
most likely net only very low dollar donors.  High dollar donors will
fall into the lower deciles, which would most likely be suppressed
from future mailings.  The lost revenue of these suppressed donors
would then offset any gains due to the increased response rate of the
low dollar donors.

Therefore, to improve the cost-effectiveness of future direct
marketing efforts, PVA wishes to develop a model that will help them
maximize the net revenue (a regression or estimation task) generated
from future renewal mailings to Lapsed donors.

POPULATION
----------

The population for this analysis will be Lapsed PVA donors who
received the June '97 renewal mailing (appeal code "97NK").
Therefore, the analysis data set contains a subset of the total
universe who received the mailing.

The analysis file includes all 191,779 Lapsed donors who received the
mailing, with responders to the mailing marked with a flag in the
TARGET_B field.  The total dollar amount of each responder's gift is
in the TARGET_D field.

The overall response rate for this direct mail promotion is 5.1%.  The
distribution of the target fields in the learning and validation files
is as follows:


  Learning Data Set
  Target Variable: Binary Indicator of Response to 97NK 
  Mailing
                                Cumulative  Cumulative
  TARGET_B   Frequency   Percent   Frequency    Percent
  ------------------------------------------------------
         0      90569      94.9       90569       94.9
         1       4843       5.1       95412      100.0


  Learning Data Set
  Target Variable: Donation Amount (in $) to 97NK Mailing   

  Variable       N          Mean   Minimum       Maximum 
  ------------------------------------------------------ 
  TARGET_D   95412     0.7930732         0   200.0000000 
  ------------------------------------------------------ 



  Validation Data Set 
  Target Variable: Binary Indicator of Response to 97NK 
  Mailing
                                Cumulative  Cumulative
  TARGET_B   Frequency   Percent   Frequency    Percent
  ------------------------------------------------------
         0      91494      94.9       91494       94.9
         1       4873       5.1       96367      100.0

  Validation Data Set 
  Target Variable: Donation Amount (in $) to 97NK Mailing 

  Variable       N          Mean   Minimum       Maximum
  ------------------------------------------------------
  TARGET_D   96367     0.7895819         0   500.0000000
  ------------------------------------------------------


The average donation amount (in $) among the responsers is: 


  Learning Data Set
  Target Variable: Donation Amount (in $) to 97NK 
  Mailing  

      N          Mean       Minimum       Maximum
  -----------------------------------------------
   4843    15.6243444     1.0000000   200.0000000
  -----------------------------------------------


  Validation Data Set
  Target Variable: Donation Amount (in $) to 97NK 
  Mailing 

      N          Mean       Minimum       Maximum
  -----------------------------------------------
   4873    15.6145372     0.3200000   500.0000000
  -----------------------------------------------


COST MATRIX
-----------

The package cost (including the mail cost) is $0.68 per piece mailed.


ANALYSIS TIME FRAME AND REFERENCE DATE
--------------------------------------

The 97NK mailing was sent out on June 1997. All information included
in the file (excluding the giving history date fields) is reflective
of behavior prior to 6/97. This date may be used as the reference date
in generating the "number of months since" or "time since" or "elapsed
time" variables. The participants could also find the reference date
information in the filed ADATE_2.  This filed contains the dates the
97NK promotion was mailed.


+--------------------------------------------------------------------+
| EVALUATION RULES                                                   |
+--------------------------------------------------------------------+

Once again, the objective of the analysis will be to maximize the net
revenue generated from this mailing - a censored regression or
estimation problem. The response variable is, thus, continuous (for 
the lack of a better common term.) Alhough we are releasing both the
binary and the continuous versions of the target variable (TARGET_B
and TARGET_D respectively), the program committee will use the
predicted value of the donation (dollar) amount (for the target
variable TARGET_D) in evaluating the results. So, returning the
predicted value of the binary target variable TARGET_B and its
associated probability/strength will not be sufficient. 

The typical outcome of predictive modeling in database marketing is 
an estimate of the expected response/return per customer in the
database. A marketer will mail to a customer so long as the expected 
return from an order exceeds the cost invested in generating the order, 
i.e., the cost of promotion. For our purpose, the package cost 
(including the mail cost) is $0.68 per piece mailed.

KDD-CUP committee will evaluate the results based solely on the net
revenue generated on the hold-out or validation sample.

The measure we will use is:

  Sum (the actual donation amount - $0.68) over all records for 
  which the expected revenue (or predicted value of the donation) 
  is over $0.68.

This is a direct measure of profit.  The winner will be the 
participant with the highest actual sum.  The results will be rounded 
to the nearest 10 dollars. 


+--------------------------------------------------------------------+
| DATA SOURCES and ORDER & TYPE OF THE VARIABLES IN THE DATA SETS    |
+--------------------------------------------------------------------+

The dataset includes:

o 24 months of detailed PVA promotion and giving history (covering the
  period 12 to 36 months prior to the "97NK" mailing)

o A summary of the promotions sent to the donors over the most recent
  12 months prior to the "97NK" mailing (by definition, none of these
  donors responded to any of these promotions)

o Summary variables reflecting each donor's lifetime giving history
  (e.g., total # of donations prior to "97NK" mailing, total $ amount
  of the donations, etc.)

o Overlay demographics, including a mix of household and area level
  data

o All other available data from the PVA database (e.g., date of first
  gift, state, origin source, etc.)

The fields are described in greater detail in the data dictionary file
<filename: cup98DIC.txt>.

The name of the variables in the learning and validation data sets is
included in each file as the top (header) record. For your
information, they are listed below again (ordered by data set
position) along with the filed type information (Num: numeric, Char:
string/character.)

  Field Name  Type  
  ----------------
  ODATEDW     Num   
  OSOURCE     Char  
  TCODE       Num   
  STATE       Char  
  ZIP         Char  
  MAILCODE    Char  
  PVASTATE    Char  
  DOB         Num   
  NOEXCH      Char  
  RECINHSE    Char  
  RECP3       Char  
  RECPGVG     Char  
  RECSWEEP    Char  
  MDMAUD      Char  
  DOMAIN      Char  
  CLUSTER     Char  
  AGE         Num   
  AGEFLAG     Char  
  HOMEOWNR    Char  
  CHILD03     Char  
  CHILD07     Char  
  CHILD12     Char  
  CHILD18     Char  
  NUMCHLD     Num   
  INCOME      Num   
  GENDER      Char  
  WEALTH1     Num   
  HIT         Num   
  MBCRAFT     Num   
  MBGARDEN    Num   
  MBBOOKS     Num   
  MBCOLECT    Num   
  MAGFAML     Num   
  MAGFEM      Num   
  MAGMALE     Num   
  PUBGARDN    Num   
  PUBCULIN    Num   
  PUBHLTH     Num   
  PUBDOITY    Num   
  PUBNEWFN    Num   
  PUBPHOTO    Num   
  PUBOPP      Num   
  DATASRCE    Char  
  MALEMILI    Num   
  MALEVET     Num   
  VIETVETS    Num   
  WWIIVETS    Num   
  LOCALGOV    Num   
  STATEGOV    Num   
  FEDGOV      Num   
  SOLP3       Char  
  SOLIH       Char  
  MAJOR       Char  
  WEALTH2     Num   
  GEOCODE     Char  
  COLLECT1    Char  
  VETERANS    Char  
  BIBLE       Char  
  CATLG       Char  
  HOMEE       Char  
  PETS        Char  
  CDPLAY      Char  
  STEREO      Char  
  PCOWNERS    Char  
  PHOTO       Char  
  CRAFTS      Char  
  FISHER      Char  
  GARDENIN    Char  
  BOATS       Char  
  WALKER      Char  
  KIDSTUFF    Char  
  CARDS       Char  
  PLATES      Char  
  LIFESRC     Char  
  PEPSTRFL    Char  
  POP901      Num   
  POP902      Num   
  POP903      Num   
  POP90C1     Num   
  POP90C2     Num   
  POP90C3     Num   
  POP90C4     Num   
  POP90C5     Num   
  ETH1        Num   
  ETH2        Num   
  ETH3        Num   
  ETH4        Num   
  ETH5        Num   
  ETH6        Num   
  ETH7        Num   
  ETH8        Num   
  ETH9        Num   
  ETH10       Num   
  ETH11       Num   
  ETH12       Num   
  ETH13       Num   
  ETH14       Num   
  ETH15       Num   
  ETH16       Num   
  AGE901      Num   
  AGE902      Num   
  AGE903      Num   
  AGE904      Num   
  AGE905      Num   
  AGE906      Num   
  AGE907      Num   
  CHIL1       Num   
  CHIL2       Num   
  CHIL3       Num   
  AGEC1       Num   
  AGEC2       Num   
  AGEC3       Num   
  AGEC4       Num   
  AGEC5       Num   
  AGEC6       Num   
  AGEC7       Num   
  CHILC1      Num   
  CHILC2      Num   
  CHILC3      Num   
  CHILC4      Num   
  CHILC5      Num   
  HHAGE1      Num   
  HHAGE2      Num   
  HHAGE3      Num   
  HHN1        Num   
  HHN2        Num   
  HHN3        Num   
  HHN4        Num   
  HHN5        Num   
  HHN6        Num   
  MARR1       Num   
  MARR2       Num   
  MARR3       Num   
  MARR4       Num   
  HHP1        Num   
  HHP2        Num   
  DW1         Num   
  DW2         Num   
  DW3         Num   
  DW4         Num   
  DW5         Num   
  DW6         Num   
  DW7         Num   
  DW8         Num   
  DW9         Num   
  HV1         Num   
  HV2         Num   
  HV3         Num   
  HV4         Num   
  HU1         Num   
  HU2         Num   
  HU3         Num   
  HU4         Num   
  HU5         Num   
  HHD1        Num   
  HHD2        Num   
  HHD3        Num   
  HHD4        Num   
  HHD5        Num   
  HHD6        Num   
  HHD7        Num   
  HHD8        Num   
  HHD9        Num   
  HHD10       Num   
  HHD11       Num   
  HHD12       Num   
  ETHC1       Num   
  ETHC2       Num   
  ETHC3       Num   
  ETHC4       Num   
  ETHC5       Num   
  ETHC6       Num   
  HVP1        Num   
  HVP2        Num   
  HVP3        Num   
  HVP4        Num   
  HVP5        Num   
  HVP6        Num   
  HUR1        Num   
  HUR2        Num   
  RHP1        Num   
  RHP2        Num   
  RHP3        Num   
  RHP4        Num   
  HUPA1       Num   
  HUPA2       Num   
  HUPA3       Num   
  HUPA4       Num   
  HUPA5       Num   
  HUPA6       Num   
  HUPA7       Num   
  RP1         Num   
  RP2         Num   
  RP3         Num   
  RP4         Num   
  MSA         Num   
  ADI         Num   
  DMA         Num   
  IC1         Num   
  IC2         Num   
  IC3         Num   
  IC4         Num   
  IC5         Num   
  IC6         Num   
  IC7         Num   
  IC8         Num   
  IC9         Num   
  IC10        Num   
  IC11        Num   
  IC12        Num   
  IC13        Num   
  IC14        Num   
  IC15        Num   
  IC16        Num   
  IC17        Num   
  IC18        Num   
  IC19        Num   
  IC20        Num   
  IC21        Num   
  IC22        Num   
  IC23        Num   
  HHAS1       Num   
  HHAS2       Num   
  HHAS3       Num   
  HHAS4       Num   
  MC1         Num   
  MC2         Num   
  MC3         Num   
  TPE1        Num   
  TPE2        Num   
  TPE3        Num   
  TPE4        Num   
  TPE5        Num   
  TPE6        Num   
  TPE7        Num   
  TPE8        Num   
  TPE9        Num   
  PEC1        Num   
  PEC2        Num   
  TPE10       Num   
  TPE11       Num   
  TPE12       Num   
  TPE13       Num   
  LFC1        Num   
  LFC2        Num   
  LFC3        Num   
  LFC4        Num   
  LFC5        Num   
  LFC6        Num   
  LFC7        Num   
  LFC8        Num   
  LFC9        Num   
  LFC10       Num   
  OCC1        Num   
  OCC2        Num   
  OCC3        Num   
  OCC4        Num   
  OCC5        Num   
  OCC6        Num   
  OCC7        Num   
  OCC8        Num   
  OCC9        Num   
  OCC10       Num   
  OCC11       Num   
  OCC12       Num   
  OCC13       Num   
  EIC1        Num   
  EIC2        Num   
  EIC3        Num   
  EIC4        Num   
  EIC5        Num   
  EIC6        Num   
  EIC7        Num   
  EIC8        Num   
  EIC9        Num   
  EIC10       Num   
  EIC11       Num   
  EIC12       Num   
  EIC13       Num   
  EIC14       Num   
  EIC15       Num   
  EIC16       Num   
  OEDC1       Num   
  OEDC2       Num   
  OEDC3       Num   
  OEDC4       Num   
  OEDC5       Num   
  OEDC6       Num   
  OEDC7       Num   
  EC1         Num   
  EC2         Num   
  EC3         Num   
  EC4         Num   
  EC5         Num   
  EC6         Num   
  EC7         Num   
  EC8         Num   
  SEC1        Num   
  SEC2        Num   
  SEC3        Num   
  SEC4        Num   
  SEC5        Num   
  AFC1        Num   
  AFC2        Num   
  AFC3        Num   
  AFC4        Num   
  AFC5        Num   
  AFC6        Num   
  VC1         Num   
  VC2         Num   
  VC3         Num   
  VC4         Num   
  ANC1        Num   
  ANC2        Num   
  ANC3        Num   
  ANC4        Num   
  ANC5        Num   
  ANC6        Num   
  ANC7        Num   
  ANC8        Num   
  ANC9        Num   
  ANC10       Num   
  ANC11       Num   
  ANC12       Num   
  ANC13       Num   
  ANC14       Num   
  ANC15       Num   
  POBC1       Num   
  POBC2       Num   
  LSC1        Num   
  LSC2        Num   
  LSC3        Num   
  LSC4        Num   
  VOC1        Num   
  VOC2        Num   
  VOC3        Num   
  HC1         Num   
  HC2         Num   
  HC3         Num   
  HC4         Num   
  HC5         Num   
  HC6         Num   
  HC7         Num   
  HC8         Num   
  HC9         Num   
  HC10        Num   
  HC11        Num   
  HC12        Num   
  HC13        Num   
  HC14        Num   
  HC15        Num   
  HC16        Num   
  HC17        Num   
  HC18        Num   
  HC19        Num   
  HC20        Num   
  HC21        Num   
  MHUC1       Num   
  MHUC2       Num   
  AC1         Num   
  AC2         Num   
  ADATE_2     Num   
  ADATE_3     Num   
  ADATE_4     Num   
  ADATE_5     Num   
  ADATE_6     Num   
  ADATE_7     Num   
  ADATE_8     Num   
  ADATE_9     Num   
  ADATE_10    Num   
  ADATE_11    Num   
  ADATE_12    Num   
  ADATE_13    Num   
  ADATE_14    Num   
  ADATE_15    Num   
  ADATE_16    Num   
  ADATE_17    Num   
  ADATE_18    Num   
  ADATE_19    Num   
  ADATE_20    Num   
  ADATE_21    Num   
  ADATE_22    Num   
  ADATE_23    Num   
  ADATE_24    Num   
  RFA_2       Char  
  RFA_3       Char  
  RFA_4       Char  
  RFA_5       Char  
  RFA_6       Char  
  RFA_7       Char  
  RFA_8       Char  
  RFA_9       Char  
  RFA_10      Char  
  RFA_11      Char  
  RFA_12      Char  
  RFA_13      Char  
  RFA_14      Char  
  RFA_15      Char  
  RFA_16      Char  
  RFA_17      Char  
  RFA_18      Char  
  RFA_19      Char  
  RFA_20      Char  
  RFA_21      Char  
  RFA_22      Char  
  RFA_23      Char  
  RFA_24      Char  
  CARDPROM    Num   
  MAXADATE    Num   
  NUMPROM     Num   
  CARDPM12    Num   
  NUMPRM12    Num   
  RDATE_3     Num   
  RDATE_4     Num   
  RDATE_5     Num   
  RDATE_6     Num   
  RDATE_7     Num   
  RDATE_8     Num   
  RDATE_9     Num   
  RDATE_10    Num   
  RDATE_11    Num   
  RDATE_12    Num   
  RDATE_13    Num   
  RDATE_14    Num   
  RDATE_15    Num   
  RDATE_16    Num   
  RDATE_17    Num   
  RDATE_18    Num   
  RDATE_19    Num   
  RDATE_20    Num   
  RDATE_21    Num   
  RDATE_22    Num   
  RDATE_23    Num   
  RDATE_24    Num   
  RAMNT_3     Num   
  RAMNT_4     Num   
  RAMNT_5     Num   
  RAMNT_6     Num   
  RAMNT_7     Num   
  RAMNT_8     Num   
  RAMNT_9     Num   
  RAMNT_10    Num   
  RAMNT_11    Num   
  RAMNT_12    Num   
  RAMNT_13    Num   
  RAMNT_14    Num   
  RAMNT_15    Num   
  RAMNT_16    Num   
  RAMNT_17    Num   
  RAMNT_18    Num   
  RAMNT_19    Num   
  RAMNT_20    Num   
  RAMNT_21    Num   
  RAMNT_22    Num   
  RAMNT_23    Num   
  RAMNT_24    Num   
  RAMNTALL    Num   
  NGIFTALL    Num   
  CARDGIFT    Num   
  MINRAMNT    Num   
  MINRDATE    Num   
  MAXRAMNT    Num   
  MAXRDATE    Num   
  LASTGIFT    Num   
  LASTDATE    Num   
  FISTDATE    Num   
  NEXTDATE    Num   
  TIMELAG     Num   
  AVGGIFT     Num   
  CONTROLN    Num   
  TARGET_B    Num   /* not included in the validation file */
  TARGET_D    Num   /* not included in the validation file */ 
  HPHONE_D    Num   
  RFA_2R      Char  
  RFA_2F      Char  
  RFA_2A      Char  
  MDMAUD_R    Char  
  MDMAUD_F    Char  
  MDMAUD_A    Char  
  CLUSTER2    Num   
  GEOCODE2    Char.  


+--------------------------------------------------------------------+
| SUMMARY STATISTICS (MIN & MAX)                                     | 
+--------------------------------------------------------------------+

Summary statistics are provided for the numeric variables only. 

  Variable         Learning Data Set         Validation Data Set 
  --------     ------------------------- --------------------------- 
                   Minimum       Maximum       Minimum       Maximum 
  --------     ------------------------- --------------------------- 
  ODATEDW          8306.00       9701.00       8301.00       9701.00 
  TCODE                  0      72002.00             0      39002.00 
  DOB                    0       9710.00             0       9705.00 
  AGE            1.0000000    98.0000000     1.0000000    98.0000000 
  NUMCHLD        1.0000000     7.0000000     1.0000000     7.0000000 
  INCOME         1.0000000     7.0000000     1.0000000     7.0000000 
  WEALTH1                0     9.0000000             0     9.0000000 
  HIT                    0   241.0000000             0   242.0000000 
  MBCRAFT                0     6.0000000             0     6.0000000 
  MBGARDEN               0     4.0000000             0     3.0000000 
  MBBOOKS                0     9.0000000             0     9.0000000 
  MBCOLECT               0     6.0000000             0     6.0000000 
  MAGFAML                0     9.0000000             0     9.0000000 
  MAGFEM                 0     5.0000000             0     4.0000000 
  MAGMALE                0     4.0000000             0     4.0000000 
  PUBGARDN               0     5.0000000             0     6.0000000 
  PUBCULIN               0     6.0000000             0     4.0000000 
  PUBHLTH                0     9.0000000             0     9.0000000 
  PUBDOITY               0     8.0000000             0     9.0000000 
  PUBNEWFN               0     9.0000000             0     9.0000000 
  PUBPHOTO               0     2.0000000             0     2.0000000 
  PUBOPP                 0     9.0000000             0     9.0000000 
  MALEMILI               0    99.0000000             0    99.0000000 
  MALEVET                0    99.0000000             0    99.0000000 
  VIETVETS               0    99.0000000             0    99.0000000 
  WWIIVETS               0    99.0000000             0    99.0000000 
  LOCALGOV               0    99.0000000             0    76.0000000 
  STATEGOV               0    99.0000000             0    99.0000000 
  FEDGOV                 0    87.0000000             0    99.0000000 
  WEALTH2                0     9.0000000             0     9.0000000 
  POP901                 0      98701.00             0     100286.00 
  POP902                 0      23766.00             0      21036.00 
  POP903                 0      35403.00             0      35403.00 
  POP90C1                0    99.0000000             0    99.0000000 
  POP90C2                0    99.0000000             0    99.0000000 
  POP90C3                0    99.0000000             0    99.0000000 
  POP90C4                0    99.0000000             0    99.0000000 
  POP90C5                0    99.0000000             0    99.0000000 
  ETH1                   0    99.0000000             0    99.0000000 
  ETH2                   0    99.0000000             0    99.0000000 
  ETH3                   0    99.0000000             0    99.0000000 
  ETH4                   0    99.0000000             0    94.0000000 
  ETH5                   0    99.0000000             0    99.0000000 
  ETH6                   0    22.0000000             0    29.0000000 
  ETH7                   0    72.0000000             0    67.0000000 
  ETH8                   0    99.0000000             0    87.0000000 
  ETH9                   0    67.0000000             0    67.0000000 
  ETH10                  0    46.0000000             0    45.0000000 
  ETH11                  0    47.0000000             0    49.0000000 
  ETH12                  0    72.0000000             0    79.0000000 
  ETH13                  0    97.0000000             0    96.0000000 
  ETH14                  0    57.0000000             0    52.0000000 
  ETH15                  0    81.0000000             0    81.0000000 
  ETH16                  0    86.0000000             0    81.0000000 
  AGE901                 0    84.0000000             0    84.0000000 
  AGE902                 0    84.0000000             0    84.0000000 
  AGE903                 0    84.0000000             0    84.0000000 
  AGE904                 0    84.0000000             0    81.0000000 
  AGE905                 0    84.0000000             0    81.0000000 
  AGE906                 0    84.0000000             0    81.0000000 
  AGE907                 0    75.0000000             0    71.0000000 
  CHIL1                  0    99.0000000             0    99.0000000 
  CHIL2                  0    99.0000000             0    99.0000000 
  CHIL3                  0    99.0000000             0    99.0000000 
  AGEC1                  0    99.0000000             0    97.0000000 
  AGEC2                  0    99.0000000             0    99.0000000 
  AGEC3                  0    99.0000000             0    99.0000000 
  AGEC4                  0    99.0000000             0    50.0000000 
  AGEC5                  0    99.0000000             0    99.0000000 
  AGEC6                  0    99.0000000             0    99.0000000 
  AGEC7                  0    99.0000000             0    90.0000000 
  CHILC1                 0    99.0000000             0    99.0000000 
  CHILC2                 0    99.0000000             0    99.0000000 
  CHILC3                 0    99.0000000             0    99.0000000 
  CHILC4                 0    99.0000000             0    99.0000000 
  CHILC5                 0    99.0000000             0    99.0000000 
  HHAGE1                 0    99.0000000             0    99.0000000 
  HHAGE2                 0    99.0000000             0    99.0000000 
  HHAGE3                 0    99.0000000             0    99.0000000 
  HHN1                   0    99.0000000             0    99.0000000 
  HHN2                   0    99.0000000             0    99.0000000 
  HHN3                   0    99.0000000             0    99.0000000 
  HHN4                   0    99.0000000             0    99.0000000 
  HHN5                   0    99.0000000             0    99.0000000 
  HHN6                   0    99.0000000             0    99.0000000 
  MARR1                  0    99.0000000             0    99.0000000 
  MARR2                  0    99.0000000             0    99.0000000 
  MARR3                  0    73.0000000             0    99.0000000 
  MARR4                  0    99.0000000             0    99.0000000 
  HHP1                   0   650.0000000             0   650.0000000 
  HHP2                   0   700.0000000             0   700.0000000 
  DW1                    0    99.0000000             0    99.0000000 
  DW2                    0    99.0000000             0    99.0000000 
  DW3                    0    99.0000000             0    88.0000000 
  DW4                    0    99.0000000             0    99.0000000 
  DW5                    0    99.0000000             0    99.0000000 
  DW6                    0    99.0000000             0    99.0000000 
  DW7                    0    99.0000000             0    99.0000000 
  DW8                    0    99.0000000             0    99.0000000 
  DW9                    0    99.0000000             0    99.0000000 
  HV1                    0       6000.00             0       6000.00 
  HV2                    0       6000.00             0       6000.00 
  HV3                    0    13.0000000             0    13.0000000 
  HV4                    0    13.0000000             0    13.0000000 
  HU1                    0    99.0000000             0    99.0000000 
  HU2                    0    99.0000000             0    99.0000000 
  HU3                    0    99.0000000             0    99.0000000 
  HU4                    0    99.0000000             0    99.0000000 
  HU5                    0    99.0000000             0    99.0000000 
  HHD1                   0    99.0000000             0    99.0000000 
  HHD2                   0    99.0000000             0    99.0000000 
  HHD3                   0    99.0000000             0    99.0000000 
  HHD4                   0    99.0000000             0    99.0000000 
  HHD5                   0    99.0000000             0    99.0000000 
  HHD6                   0    99.0000000             0    99.0000000 
  HHD7                   0    99.0000000             0    99.0000000 
  HHD8                   0    50.0000000             0    31.0000000 
  HHD9                   0    99.0000000             0    99.0000000 
  HHD10                  0    99.0000000             0    99.0000000 
  HHD11                  0    99.0000000             0    99.0000000 
  HHD12                  0    99.0000000             0    99.0000000 
  ETHC1                  0    75.0000000             0    71.0000000 
  ETHC2                  0    99.0000000             0    99.0000000 
  ETHC3                  0    99.0000000             0    99.0000000 
  ETHC4                  0    55.0000000             0    46.0000000 
  ETHC5                  0    99.0000000             0    83.0000000 
  ETHC6                  0    99.0000000             0    80.0000000 
  HVP1                   0    99.0000000             0    99.0000000 
  HVP2                   0    99.0000000             0    99.0000000 
  HVP3                   0    99.0000000             0    99.0000000 
  HVP4                   0    99.0000000             0    99.0000000 
  HVP5                   0    99.0000000             0    99.0000000 
  HVP6                   0    99.0000000             0    99.0000000 
  HUR1                   0    99.0000000             0    99.0000000 
  HUR2                   0    99.0000000             0    99.0000000 
  RHP1                   0    85.0000000             0    85.0000000 
  RHP2                   0    90.0000000             0    90.0000000 
  RHP3                   0    61.0000000             0    61.0000000 
  RHP4                   0    40.0000000             0    40.0000000 
  HUPA1                  0    99.0000000             0    99.0000000 
  HUPA2                  0    99.0000000             0    99.0000000 
  HUPA3                  0    99.0000000             0    99.0000000 
  HUPA4                  0    99.0000000             0    99.0000000 
  HUPA5                  0    99.0000000             0    99.0000000 
  HUPA6                  0    99.0000000             0    99.0000000 
  HUPA7                  0    99.0000000             0    99.0000000 
  RP1                    0    99.0000000             0    99.0000000 
  RP2                    0    99.0000000             0    99.0000000 
  RP3                    0    99.0000000             0    99.0000000 
  RP4                    0    99.0000000             0    99.0000000 
  MSA                    0       9360.00             0       9360.00 
  ADI                    0   651.0000000             0   645.0000000 
  DMA                    0   881.0000000             0   881.0000000 
  IC1                    0       1500.00             0       1500.00 
  IC2                    0       1500.00             0       1500.00 
  IC3                    0       1500.00             0       1394.00 
  IC4                    0       1500.00             0       1500.00 
  IC5                    0     174523.00             0     174523.00 
  IC6                    0    99.0000000             0    99.0000000 
  IC7                    0    99.0000000             0    99.0000000 
  IC8                    0    99.0000000             0    99.0000000 
  IC9                    0    99.0000000             0    99.0000000 
  IC10                   0    99.0000000             0    99.0000000 
  IC11                   0    99.0000000             0    99.0000000 
  IC12                   0    50.0000000             0    57.0000000 
  IC13                   0    61.0000000             0    61.0000000 
  IC14                   0    99.0000000             0    78.0000000 
  IC15                   0    99.0000000             0    99.0000000 
  IC16                   0    99.0000000             0    99.0000000 
  IC17                   0    99.0000000             0    99.0000000 
  IC18                   0    99.0000000             0    99.0000000 
  IC19                   0    99.0000000             0    99.0000000 
  IC20                   0    99.0000000             0    99.0000000 
  IC21                   0    50.0000000             0    99.0000000 
  IC22                   0    99.0000000             0    99.0000000 
  IC23                   0    99.0000000             0    99.0000000 
  HHAS1                  0    99.0000000             0    99.0000000 
  HHAS2                  0    99.0000000             0    99.0000000 
  HHAS3                  0    99.0000000             0    99.0000000 
  HHAS4                  0    99.0000000             0    99.0000000 
  MC1                    0    99.0000000             0    99.0000000 
  MC2                    0    99.0000000             0    99.0000000 
  MC3                    0    99.0000000             0    99.0000000 
  TPE1                   0    99.0000000             0    99.0000000 
  TPE2                   0    99.0000000             0    99.0000000 
  TPE3                   0    99.0000000             0    99.0000000 
  TPE4                   0    99.0000000             0    99.0000000 
  TPE5                   0    71.0000000             0    68.0000000 
  TPE6                   0    47.0000000             0    47.0000000 
  TPE7                   0    25.0000000             0    44.0000000 
  TPE8                   0    99.0000000             0    99.0000000 
  TPE9                   0    99.0000000             0    99.0000000 
  PEC1                   0    99.0000000             0    97.0000000 
  PEC2                   0    99.0000000             0    99.0000000 
  TPE10                  0    90.0000000             0    90.0000000 
  TPE11                  0    76.0000000             0    76.0000000 
  TPE12                  0    99.0000000             0    85.0000000 
  TPE13                  0    99.0000000             0    99.0000000 
  LFC1                   0    99.0000000             0    99.0000000 
  LFC2                   0    99.0000000             0    99.0000000 
  LFC3                   0    99.0000000             0    99.0000000 
  LFC4                   0    99.0000000             0    99.0000000 
  LFC5                   0    99.0000000             0    99.0000000 
  LFC6                   0    99.0000000             0    99.0000000 
  LFC7                   0    99.0000000             0    99.0000000 
  LFC8                   0    99.0000000             0    99.0000000 
  LFC9                   0    99.0000000             0    99.0000000 
  LFC10                  0    99.0000000             0    99.0000000 
  OCC1                   0    99.0000000             0    99.0000000 
  OCC2                   0    99.0000000             0    99.0000000 
  OCC3                   0    99.0000000             0    99.0000000 
  OCC4                   0    99.0000000             0    99.0000000 
  OCC5                   0    99.0000000             0    99.0000000 
  OCC6                   0    43.0000000             0    44.0000000 
  OCC7                   0    55.0000000             0    55.0000000 
  OCC8                   0    99.0000000             0    99.0000000 
  OCC9                   0    99.0000000             0    99.0000000 
  OCC10                  0    99.0000000             0    99.0000000 
  OCC11                  0    99.0000000             0    99.0000000 
  OCC12                  0    99.0000000             0    99.0000000 
  OCC13                  0    99.0000000             0    88.0000000 
  EIC1                   0    99.0000000             0    99.0000000 
  EIC2                   0    65.0000000             0    65.0000000 
  EIC3                   0    99.0000000             0    99.0000000 
  EIC4                   0    99.0000000             0    99.0000000 
  EIC5                   0    99.0000000             0    99.0000000 
  EIC6                   0    64.0000000             0    99.0000000 
  EIC7                   0    99.0000000             0    57.0000000 
  EIC8                   0    99.0000000             0    99.0000000 
  EIC9                   0    99.0000000             0    99.0000000 
  EIC10                  0    99.0000000             0    99.0000000 
  EIC11                  0    99.0000000             0    99.0000000 
  EIC12                  0    67.0000000             0    61.0000000 
  EIC13                  0    99.0000000             0    99.0000000 
  EIC14                  0    99.0000000             0    72.0000000 
  EIC15                  0    99.0000000             0    99.0000000 
  EIC16                  0    99.0000000             0    71.0000000 
  OEDC1                  0    99.0000000             0    99.0000000 
  OEDC2                  0    99.0000000             0    74.0000000 
  OEDC3                  0    99.0000000             0    99.0000000 
  OEDC4                  0    99.0000000             0    99.0000000 
  OEDC5                  0    99.0000000             0    99.0000000 
  OEDC6                  0    99.0000000             0    99.0000000 
  OEDC7                  0    99.0000000             0    99.0000000 
  EC1                    0   170.0000000             0   170.0000000 
  EC2                    0    99.0000000             0    99.0000000 
  EC3                    0    99.0000000             0    99.0000000 
  EC4                    0    99.0000000             0    99.0000000 
  EC5                    0    99.0000000             0    99.0000000 
  EC6                    0    37.0000000             0    68.0000000 
  EC7                    0    99.0000000             0    99.0000000 
  EC8                    0    99.0000000             0    74.0000000 
  SEC1                   0    97.0000000             0    91.0000000 
  SEC2                   0    99.0000000             0    99.0000000 
  SEC3                   0    30.0000000             0    20.0000000 
  SEC4                   0    72.0000000             0    72.0000000 
  SEC5                   0    99.0000000             0    99.0000000 
  AFC1                   0    97.0000000             0    95.0000000 
  AFC2                   0    99.0000000             0    98.0000000 
  AFC3                   0    78.0000000             0    78.0000000 
  AFC4                   0    99.0000000             0    99.0000000 
  AFC5                   0    99.0000000             0    99.0000000 
  AFC6                   0    30.0000000             0    50.0000000 
  VC1                    0    99.0000000             0    99.0000000 
  VC2                    0    99.0000000             0    99.0000000 
  VC3                    0    99.0000000             0    99.0000000 
  VC4                    0    99.0000000             0    99.0000000 
  ANC1                   0    83.0000000             0    74.0000000 
  ANC2                   0    99.0000000             0    73.0000000 
  ANC3                   0    31.0000000             0    41.0000000 
  ANC4                   0    92.0000000             0    99.0000000 
  ANC5                   0    47.0000000             0    48.0000000 
  ANC6                   0    14.0000000             0    23.0000000 
  ANC7                   0    99.0000000             0    57.0000000 
  ANC8                   0    55.0000000             0    99.0000000 
  ANC9                   0    68.0000000             0    57.0000000 
  ANC10                  0    99.0000000             0    74.0000000 
  ANC11                  0    43.0000000             0    74.0000000 
  ANC12                  0    52.0000000             0    38.0000000 
  ANC13                  0    50.0000000             0    50.0000000 
  ANC14                  0    27.0000000             0    33.0000000 
  ANC15                  0    32.0000000             0    47.0000000 
  POBC1                  0    99.0000000             0    99.0000000 
  POBC2                  0    99.0000000             0    99.0000000 
  LSC1                   0    99.0000000             0    99.0000000 
  LSC2                   0    99.0000000             0    99.0000000 
  LSC3                   0    99.0000000             0    99.0000000 
  LSC4                   0    99.0000000             0    99.0000000 
  VOC1                   0    99.0000000             0    99.0000000 
  VOC2                   0    99.0000000             0    99.0000000 
  VOC3                   0    99.0000000             0    99.0000000 
  HC1                    0    31.0000000             0    31.0000000 
  HC2                    0    52.0000000             0    52.0000000 
  HC3                    0    99.0000000             0    99.0000000 
  HC4                    0    99.0000000             0    99.0000000 
  HC5                    0    99.0000000             0    99.0000000 
  HC6                    0    99.0000000             0    99.0000000 
  HC7                    0    99.0000000             0    99.0000000 
  HC8                    0    99.0000000             0    99.0000000 
  HC9                    0    90.0000000             0    91.0000000 
  HC10                   0    62.0000000             0    62.0000000 
  HC11                   0    99.0000000             0    99.0000000 
  HC12                   0    99.0000000             0    99.0000000 
  HC13                   0    99.0000000             0    99.0000000 
  HC14                   0    99.0000000             0    99.0000000 
  HC15                   0    30.0000000             0    34.0000000 
  HC16                   0    99.0000000             0    99.0000000 
  HC17                   0    99.0000000             0    99.0000000 
  HC18                   0    99.0000000             0    99.0000000 
  HC19                   0    99.0000000             0    99.0000000 
  HC20                   0    99.0000000             0    99.0000000 
  HC21                   0    99.0000000             0    99.0000000 
  MHUC1                  0    21.0000000             0    21.0000000 
  MHUC2                  0     5.0000000             0     5.0000000 
  AC1                    0    99.0000000             0    52.0000000 
  AC2                    0    99.0000000             0    99.0000000 
  ADATE_2          9704.00       9706.00       9704.00       9706.00 
  ADATE_3          9604.00       9606.00       9604.00       9606.00 
  ADATE_4          9511.00       9609.00       9511.00       9609.00 
  ADATE_5          9604.00       9604.00       9604.00       9604.00 
  ADATE_6          9601.00       9603.00       9601.00       9603.00 
  ADATE_7          9512.00       9602.00       9512.00       9602.00 
  ADATE_8          9511.00       9605.00       9511.00       9603.00 
  ADATE_9          9509.00       9511.00       9509.00       9511.00 
  ADATE_10         9510.00       9511.00       9510.00       9511.00 
  ADATE_11         9508.00       9511.00       9508.00       9511.00 
  ADATE_12         9507.00       9510.00       9507.00       9510.00 
  ADATE_13         9502.00       9507.00       9502.00       9507.00 
  ADATE_14         9504.00       9506.00       9504.00       9506.00 
  ADATE_15         9504.00       9504.00       9504.00       9504.00 
  ADATE_16         9502.00       9504.00       9502.00       9504.00 
  ADATE_17         9501.00       9503.00       9501.00       9503.00 
  ADATE_18         9409.00       9508.00       9409.00       9508.00 
  ADATE_19         9409.00       9411.00       9409.00       9411.00 
  ADATE_20         9411.00       9412.00       9411.00       9412.00 
  ADATE_21         9409.00       9410.00       9409.00       9410.00 
  ADATE_22         9408.00       9506.00       9408.00       9506.00 
  ADATE_23         9312.00       9407.00       9312.00       9407.00 
  ADATE_24         9405.00       9406.00       9405.00       9406.00 
  CARDPROM       1.0000000    61.0000000             0    62.0000000 
  MAXADATE         9608.00       9702.00       9607.00       9702.00 
  NUMPROM        4.0000000   195.0000000     4.0000000   189.0000000 
  CARDPM12               0    19.0000000             0    21.0000000 
  NUMPRM12       1.0000000    78.0000000     1.0000000    76.0000000 
  RDATE_3          9605.00       9806.00       9309.00       9806.00 
  RDATE_4          9510.00       9804.00       9509.00       9805.00 
  RDATE_5          9604.00       9803.00       9604.00       9805.00 
  RDATE_6          9510.00       9805.00       9511.00       9806.00 
  RDATE_7          9512.00       9610.00       9511.00       9701.00 
  RDATE_8          9511.00       9806.00       9512.00       9806.00 
  RDATE_9          9509.00       9609.00       9509.00       9603.00 
  RDATE_10         9510.00       9806.00       9511.00       9804.00 
  RDATE_11         9509.00       9805.00       9509.00       9606.00 
  RDATE_12         9509.00       9806.00       9509.00       9804.00 
  RDATE_13         9502.00       9603.00       9502.00       9803.00 
  RDATE_14         9406.00       9603.00       9505.00       9603.00 
  RDATE_15         9412.00       9603.00       9412.00       9603.00 
  RDATE_16         9411.00       9805.00       9410.00       9603.00 
  RDATE_17         9502.00       9512.00       9502.00       9512.00 
  RDATE_18         9412.00       9601.00       9407.00       9602.00 
  RDATE_19         9409.00       9509.00       9409.00       9509.00 
  RDATE_20         9411.00       9508.00       9411.00       9508.00 
  RDATE_21         9409.00       9508.00       9409.00       9508.00 
  RDATE_22         9409.00       9510.00       9409.00       9508.00 
  RDATE_23         9309.00       9507.00       9309.00       9507.00 
  RDATE_24         9309.00       9504.00       9309.00       9504.00 
  RAMNT_3        2.0000000    50.0000000     2.0000000   200.0000000 
  RAMNT_4        1.0000000   100.0000000     1.0000000   100.0000000 
  RAMNT_5        4.0000000    50.0000000     5.0000000    30.0000000 
  RAMNT_6        1.0000000   100.0000000     1.0000000   100.0000000 
  RAMNT_7        1.0000000   250.0000000     1.0000000   203.0000000 
  RAMNT_8        1.0000000   500.0000000     0.3200000       3713.31 
  RAMNT_9        1.0000000       1000.00     1.0000000   300.0000000 
  RAMNT_10       0.3000000   500.0000000     1.0000000      10000.00 
  RAMNT_11       1.0000000   300.0000000     1.0000000       1000.00 
  RAMNT_12       1.0000000   300.0000000     1.0000000   500.0000000 
  RAMNT_13       0.1000000   500.0000000     1.0000000   300.0000000 
  RAMNT_14       1.0000000   200.0000000     1.0000000   600.0000000 
  RAMNT_15       1.0000000   300.0000000     1.0000000   500.0000000 
  RAMNT_16       0.5000000   500.0000000     0.5000000   205.0000000 
  RAMNT_17       1.0000000   500.0000000     1.0000000   500.0000000 
  RAMNT_18       1.0000000       1000.00     0.3200000   300.0000000 
  RAMNT_19       1.0000000   970.0000000     1.0000000   250.0000000 
  RAMNT_20       0.5000000   250.0000000     1.0000000   200.0000000 
  RAMNT_21       1.0000000   300.0000000     1.0000000       1000.00 
  RAMNT_22       0.2900000   300.0000000     1.0000000   500.0000000 
  RAMNT_23       0.3000000   200.0000000     1.0000000   300.0000000 
  RAMNT_24       1.0000000   225.0000000     0.5000000   250.0000000 
  RAMNTALL      13.0000000       9485.00    13.0000000      10253.00 
  NGIFTALL       1.0000000   237.0000000     1.0000000   126.0000000 
  CARDGIFT               0    41.0000000             0    45.0000000 
  MINRAMNT               0       1000.00             0   436.0000000 
  MINRDATE         7506.00       9702.00       8010.00       9702.00 
  MAXRAMNT       5.0000000       5000.00     5.0000000      10000.00 
  MAXRDATE         7510.00       9702.00       8011.00       9702.00 
  LASTGIFT               0       1000.00             0      10000.00 
  LASTDATE         9503.00       9702.00       9503.00       9702.00 
  FISTDATE               0       9603.00             0       9603.00 
  NEXTDATE         7211.00       9702.00       7312.00       9702.00 
  TIMELAG                0       1088.00             0       1060.00 
  AVGGIFT        1.2857143       1000.00     1.5789474   650.0000000 
  CONTROLN       1.0000000     191779.00     3.0000000     191776.00 
  TARGET_B               0     1.0000000             0     1.0000000 
  TARGET_D               0   200.0000000             0   500.0000000 
  HPHONE_D               0     1.0000000             0     1.0000000 
  CLUSTER2       1.0000000    62.0000000     1.0000000    62.0000000
  --------------------------------------   -------------------------

        
+--------------------------------------------------------------------+
| DATA (PRE)PROCESSING                                               |
+--------------------------------------------------------------------+

General 
-------

o The field CONTROLN is a unique record identifier (an index) and
should not be used in modeling

o Response flag (field name: TARGET_B) indicates whether or not the
lapsed donor responded to the campaign. THIS FIELD SHOULD NOT BE USED
DURING MODEL BUILDING.

o Blanks in string or character variables correspond to missing
values.  Periods and/or blanks in the numeric variables correspond to
missing values.

Data preprocessing tasks include the following:

Noisy Data
----------

Some of the fields in the analysis file may contain data entry and/or
formatting errors. You are expected to clean these fields (without
excluding the records.)

Records and Fields with Missing and Sparse Data
-----------------------------------------------

Discovery methods vary in the way they treat the missing values. While
some simply disregard missing values or omit the corresponding
records, others infer missing values from known values, or treat
missing data as a special value to be included additionally in the
attribute domain.

For the purposes of KDD-CUP-98 the records and/or fields should not be
omitted from analysis because they contain missing data. Instead, the
missing data should be inferred from known values (e.g., mean, median,
mode, a modeled value, or any other way supported by your tool.) One
exception to this rule is the attributes containing 99.5 percent or
more missings. You are expected to omit these attributes from the
analysis.

You are also expected to drop attributes with 'sparse'
distributions. Sparse data occur when the events actually represented
in given data make only a very small subset of the event space.

Fields Containing Constants
---------------------------

Fields containing a constant value (i.e., there is only one value for
all the records) should be dropped from the analysis. Attributes
containing missing and one valid level (e.g., 'Y') are not considered
as constants and should be included in the analysis.

Time Frame and Date Fields
--------------------------

This mailing was mailed to a total of 3.5 million PVA donors who were
on the PVA database as of June 1997. All information contained in the
analysis dataset reflects the donor status prior to 6/97 (except the
gift receipt dates, which will follow the promotion dates.) This date
could be used as the "end date" or "rerefence date" in the calculation
of "number of months since" variables.

ATTRIBUTE TYPE
--------------

See the data dictionary to determine the attribute types. 


+--------------------------------------------------------------------+
| KDD-CUP-98 Program Committee                                       |
+--------------------------------------------------------------------+

o Vasant Dhar, New York University, New York, NY
o Tom Fawcett, Bell Atlantic, New York, NY
o Georges Grinstein, University of Massachusetts, Lowell, MA
o Ismail Parsa, Epsilon, Burlington, MA
o Gregory Piatetsky-Shapiro, Knowledge Stream Partners, Boston, MA
o Foster Provost, Bell Atlantic, New York, NY
o Kyusoek Shim, Bell Laboratories, Murray Hill, NJ


+--------------------------------------------------------------------+
| TERMINOLOGY-GLOSSARY                                               |
+--------------------------------------------------------------------+

[GLOSSARY]

For more information on the terminology used throughout this
documentation, refer to the questionnaire documentation (file name:
cup98QUE.txt.)

o attribute = field = variable = feature
o responders = targets
o non-reponders = non-targets 
o output = target = dependent variable
o inputs = independent variables
o analysis file = analysis sample = combined learning and validation 
  files 

======================================================================
EPSILON CONFIDENTIAL      EPSILON CONFIDENTIAL    EPSILON CONFIDENTIAL

    INFORMATION LISTED BELOW IS AVAILABLE UNDER THE TERMS OF THE  
                      CONFIDENTIALITY AGREEMENT                

EPSILON CONFIDENTIAL      EPSILON CONFIDENTIAL    EPSILON CONFIDENTIAL
======================================================================


```

## Data Set Dictionary {#data-set-dictionary}

```
======================================================================
EPSILON CONFIDENTIAL      EPSILON CONFIDENTIAL    EPSILON CONFIDENTIAL

    INFORMATION LISTED BELOW IS AVAILABLE UNDER THE TERMS OF THE  
                      CONFIDENTIALITY AGREEMENT                

EPSILON CONFIDENTIAL      EPSILON CONFIDENTIAL    EPSILON CONFIDENTIAL
======================================================================

+--------------------------------------------------------------------+
|                PARALYZED VETERANS OF AMERICA (PVA)                 |
|                  DATA DICTIONARY TO ACCOMPANY                      |
|                                                                    |
|                          KDD-CUP-98                                |
|                                                                    |
|          The Second International Knowledge Discovery and          |
|                 Data Mining Tools Competition                      |
|                                                                    |
|                Held in Conjunction with KDD-98                     |
|                                                                    |
|          The Fourth International Conference on Knowledge          |
|                   Discovery and Data Mining                        |
|                    [www.kdnuggets.com] or                          |
|                 [www-aig.jpl.nasa.gov/kdd98] or                    |
|                [www.aaai.org/Conferences/KDD/1998]                 |
|                                                                    |
|                       Sponsored by the                             |
|                                                                    |
|      American Association for Artificial Intelligence (AAAI)       |
|                  Epsilon Data Mining Laboratory                    |
|                Paralyzed Veterans of America (PVA)                 |
+--------------------------------------------------------------------+
|                                                                    |
| Created:     7/20/98                                               |
| Last update: 7/20/98                                               |
| file name:   cup98DIC.txt                                          |
|                                                                    |
+--------------------------------------------------------------------+

Variable                    Description
--------------------------  ------------------------------------------
ODATEDW                     Origin Date. Date of donor's first gift
                            to PVA YYMM format (Year/Month).
                           
OSOURCE                     Origin Source 
                            - (Only 1rst 3 bytes are used)
                            - Defaulted to 00000 for conversion
                            - Code indicating which mailing list the
                              donor was originally acquired from
                            - A nominal or symbolic field.
                           
TCODE                       Donor title code 
                            000    = _                     
                            001    = MR.                   
                            001001 = MESSRS.               
                            001002 = MR. & MRS.            
                            002    = MRS.                  
                            002002 = MESDAMES              
                            003    = MISS                  
                            003003 = MISSES                
                            004    = DR.                   
                            004002 = DR. & MRS.            
                            004004 = DOCTORS               
                            005    = MADAME                
                            006    = SERGEANT              
                            009    = RABBI                 
                            010    = PROFESSOR             
                            010002 = PROFESSOR & MRS.      
                            010010 = PROFESSORS            
                            011    = ADMIRAL               
                            011002 = ADMIRAL & MRS.        
                            012    = GENERAL               
                            012002 = GENERAL & MRS.        
                            013    = COLONEL               
                            013002 = COLONEL & MRS.        
                            014    = CAPTAIN               
                            014002 = CAPTAIN & MRS.        
                            015    = COMMANDER             
                            015002 = COMMANDER & MRS.      
                            016    = DEAN                  
                            017    = JUDGE                 
                            017002 = JUDGE & MRS.          
                            018    = MAJOR                 
                            018002 = MAJOR & MRS.          
                            019    = SENATOR               
                            020    = GOVERNOR              
                            021002 = SERGEANT & MRS.       
                            022002 = COLNEL & MRS.         
                            024    = LIEUTENANT            
                            026    = MONSIGNOR             
                            027    = REVEREND              
                            028    = MS.                   
                            028028 = MSS.                  
                            029    = BISHOP                
                            031    = AMBASSADOR            
                            031002 = AMBASSADOR & MRS.     
                            033    = CANTOR                
                            036    = BROTHER               
                            037    = SIR                   
                            038    = COMMODORE             
                            040    = FATHER                
                            042    = SISTER                
                            043    = PRESIDENT             
                            044    = MASTER                
                            046    = MOTHER                
                            047    = CHAPLAIN              
                            048    = CORPORAL              
                            050    = ELDER                 
                            056    = MAYOR                 
                            059002 = LIEUTENANT & MRS.     
                            062    = LORD                  
                            063    = CARDINAL              
                            064    = FRIEND                
                            065    = FRIENDS               
                            068    = ARCHDEACON            
                            069    = CANON                 
                            070    = BISHOP                
                            072002 = REVEREND & MRS.       
                            073    = PASTOR                
                            075    = ARCHBISHOP            
                            085    = SPECIALIST            
                            087    = PRIVATE               
                            089    = SEAMAN                
                            090    = AIRMAN                
                            091    = JUSTICE               
                            092    = MR. JUSTICE           
                            100    = M.                    
                            103    = MLLE.                 
                            104    = CHANCELLOR            
                            106    = REPRESENTATIVE        
                            107    = SECRETARY             
                            108    = LT. GOVERNOR          
                            109    = LIC.                  
                            111    = SA.                   
                            114    = DA.                   
                            116    = SR.                   
                            117    = SRA.                  
                            118    = SRTA.                 
                            120    = YOUR MAJESTY          
                            122    = HIS HIGHNESS          
                            123    = HER HIGHNESS          
                            124    = COUNT                 
                            125    = LADY                  
                            126    = PRINCE                
                            127    = PRINCESS              
                            128    = CHIEF                 
                            129    = BARON                 
                            130    = SHEIK                 
                            131    = PRINCE AND PRINCESS   
                            132    = YOUR IMPERIAL MAJEST  
                            135    = M. ET MME.            
                            210    = PROF.                 
                            
STATE                       State abbreviation (a nominal/symbolic field)
ZIP                         Zipcode (a nominal/symbolic field)
MAILCODE                    Mail Code
                            " "= Address is OK
                            B = Bad Address
                           
PVASTATE                    EPVA State or PVA State
                            Indicates whether the donor lives in a state 
                            served by the organization's EPVA chapter
                            P = PVA State
                            E = EPVA State (Northeastern US)
                           
DOB                         Date of birth (YYMM, Year/Month format.)
NOEXCH                      Do Not Exchange Flag (For list rental)
                            _ = can be exchanged
                            X = do not exchange
                           
RECINHSE                    In House File Flag
                            _ = Not an In House Record
                            X = Donor has given to PVA's In House program
                           
RECP3                       P3 File Flag
                            _ = Not a P3 Record
                            X = Donor has given to PVA's P3 program
                           
RECPGVG                     Planned Giving File Flag
                            _ = Not a Planned Giving Record
                            X = Planned Giving Record
                           
RECSWEEP                    Sweepstakes file flag
                            _ = Not a Sweepstakes Record
                            X = Sweepstakes Record
                           
MDMAUD                      The Major Donor Matrix code
                            The codes describe frequency and amount of
                            giving for donors who have given a $100+
                            gift at any time in their giving history.
                            An RFA (recency/frequency/monetary) field.

                            The (current) concatenated version is a nominal 
                            or symbolic field. The individual bytes could separately be 
                            used as fields and refer to the following: 
  
                            First byte: Recency of Giving
                              C=Current Donor
                              L=Lapsed Donor
                              I=Inactive Donor
                              D=Dormant Donor
                           
                            2nd byte: Frequency of Giving
                              1=One gift in the period of recency
                              2=Two-Four gifts in the period of recency
                              5=Five+ gifts in the period of recency
                           
                            3rd byte: Amount of Giving
                              L=Less than $100(Low Dollar)
                              C=$100-499(Core)
                              M=$500-999(Major)
                              T=$1,000+(Top)
                           
                            4th byte: Blank/meaningless/filler

                            'X' indicates that the donor is not a major donor. 
 
                            For more information regarding the RFA codes, see 
                            the promotion history field definitions. 

DOMAIN                      DOMAIN/Cluster code. A nominal or symbolic field. 
                            could be broken down by bytes as explained below.  
                           
                            1st byte = Urbanicity level of the donor's neighborhood
                              U=Urban
                              C=City
                              S=Suburban
                              T=Town
                              R=Rural
                           
                            2nd byte = Socio-Economic status of the neighborhood
                              1 = Highest SES
                              2 = Average SES
                              3 = Lowest SES (except for Urban communities, where 
                                  1 = Highest SES, 2 = Above average SES, 
                                  3 = Below average SES, 4 = Lowest SES.) 
                           
CLUSTER                     CLUSTER
                            Code indicating which cluster group the donor falls into.  
                            Each cluster is unique in terms of socio-economic status, 
                            urbanicty, ethnicity and a variety of other demographic 
                            characteristics. A nominal or symbolic field.
                           
AGE                         Overlay Age 
                            0 = missing
                           
AGEFLAG                     Age Flag
                            E = Exact
                            I = Inferred from Date of Birth Field
                           
HOMEOWNR                    Home Owner Flag
                            H = Home owner 
                            U = Unknown
                           
CHILD03                     Presence of Children age 0-3
                            B = Both, F = Female, M = Male
                           
CHILD07                     Presence of Childern age 4-7
CHILD12                     Presence of Childern age 8-12
CHILD18                     Presence of Childern age 13-18
                           
NUMCHLD                     NUMBER OF CHILDREN
INCOME                      HOUSEHOLD INCOME
GENDER                      Gender
                            M = Male
                            F = Female
                            U = Unknown
                            J = Joint Account, unknown gender
                           
WEALTH1                     Wealth Rating
HIT                         MOR Flag # HIT (Mail Order Response)
                            Indicates total number of known times the donor has 
                            responded to a mail order offer other than PVA's.
                           
--------------------------  -------------------------------------------------
                            The following variables indicate the number of 
                            known times the donor has responded to other 
                            types of mail order offers.
                           
MBCRAFT                     Buy Craft Hobby
MBGARDEN                    Buy Gardening
MBBOOKS                     Buy Books
MBCOLECT                    Buy Collectables
MAGFAML                     Buy General Family Mags
MAGFEM                      Buy Female Mags
MAGMALE                     Buy Sports Mags
PUBGARDN                    Gardening Pubs
PUBCULIN                    Culinary Pubs
PUBHLTH                     Health Pubs
PUBDOITY                    Do It Yourself Pubs
PUBNEWFN                    News / Finance Pubs
PUBPHOTO                    Photography Pubs
PUBOPP                      Opportunity Seekers Pubs
                           
--------------------------  -------------------------------------------------
                           
DATASRCE                    Source of Overlay Data
                            Indicates which third-party data source the donor 
                            matched against
                            1 = MetroMail
                            2 = Polk
                            3 = Both
                           
MALEMILI                    % Males active in the Military
MALEVET                     % Males Veterans
VIETVETS                    % Vietnam Vets
WWIIVETS                    % WWII Vets
LOCALGOV                    % Employed by Local Gov
STATEGOV                    % Employed by State Gov
FEDGOV                      % Employed by Fed Gov
                           
SOLP3                       SOLICIT LIMITATION CODE P3
                               = can be mailed (Default)
                            00 = Do Not Solicit or Mail
                            01 = one solicitation per year
                            02 = two solicitations per year
                            03 = three solicitations per year
                            04 = four solicitations per year
                            05 = five solicitations per year
                            06 = six solicitations per year
                            12 = twelve solicitations per year
                           
SOLIH                       SOLICITATION LIMIT CODE IN HOUSE
                               = can be mailed (Default)
                            00 = Do Not Solicit
                            01 = one solicitation per year
                            02 = two solicitations per year
                            03 = three solicitations per year
                            04 = four solicitations per year
                            05 = five solicitations per year
                            06 = six solicitations per year
                            12 = twelve solicitations per year
                           
MAJOR                       Major ($$) Donor Flag
                            _ = Not a Major Donor
                            X = Major Donor
                           
WEALTH2                     Wealth Rating
                            Wealth rating uses median family income and
                            population statistics from each area to
                            index relative wealth within each state
                            The segments are denoted 0-9, with 9 being
                            the highest income group and zero being the
                            lowest. Each rating has a different meaning
                            within each state.
                           
GEOCODE                     Geo Cluster Code indicating the level geography at which 
                            a record matches the census data.  
                            A nominal or symbolic field.
                            Blank=No code has been assigned or did not 
                            match at any level.
                           
--------------------------  -------------------------------------------------
                            The following variables reflect donor interests, 
                            as collected from third-party data sources
                           
COLLECT1                    COLLECTABLE (Y/N)
VETERANS                    VETERANS (Y/N)
BIBLE                       BIBLE READING (Y/N)
CATLG                       SHOP BY CATALOG (Y/N)
HOMEE                       WORK FROM HOME (Y/N)
PETS                        HOUSEHOLD PETS (Y/N)
CDPLAY                      CD PLAYER OWNERS (Y/N)
STEREO                      STEREO/RECORDS/TAPES/CD (Y/N)
PCOWNERS                    HOME PC OWNERS/USERS
PHOTO                       PHOTOGRAPHY (Y/N)
CRAFTS                      CRAFTS (Y/N)
FISHER                      FISHING (Y/N)
GARDENIN                    GARDENING (Y/N)
BOATS                       POWER BOATING (Y/N)
WALKER                      WALK FOR HEALTH (Y/N)
KIDSTUFF                    BUYS CHILDREN'S PRODUCTS (Y/N)
CARDS                       STATIONARY/CARDS BUYER (Y/N)
PLATES                      PLATE COLLECTOR (Y/N)
                           
LIFESRC                     LIFE STYLE DATA SOURCE
                            Indicates source of the lifestyle variables listed 
                            above
                            1 = MATCHED ON METRO MAIL ONLY
                            2 = MATCHED ON POLK ONLY
                            3 = MATCHED BOTH MM AND POLK

--------------------------  -------------------------------------------------
                           
PEPSTRFL                    Indicates PEP Star RFA Status
                            blank = Not considered to be a PEP Star
                            'X'   = Has PEP Star RFA Status
                           
--------------------------  -------------------------------------------------
                           
                            The following variables reflect characteristics 
                            of the donors neighborhood, as collected from the 
                            1990 US Census.
                           
POP901                      Number of Persons
POP902                      Number of Families
POP903                      Number of Households
POP90C1                     Percent Population in Urbanized Area
POP90C2                     Percent Population Outside Urbanized Area
POP90C3                     Percent Population Inside Rural Area
POP90C4                     Percent Male
POP90C5                     Percent Female
ETH1                        Percent White
ETH2                        Percent Black
ETH3                        Percent Native American
ETH4                        Percent Pacific Islander/Asian
ETH5                        Percent Hispanic
ETH6                        Percent Asian Indian
ETH7                        Percent Japanese
ETH8                        Percent Chinese
ETH9                        Percent Philipino
ETH10                       Percent Korean
ETH11                       Percent Vietnamese
ETH12                       Percent Hawaiian
ETH13                       Percent Mexican
ETH14                       Percent Puerto Rican
ETH15                       Percent Cuban
ETH16                       Percent Other Hispanic
AGE901                      Median Age of Population
AGE902                      Median Age of Adults 18 or Older
AGE903                      Median Age of Adults 25 or Older
AGE904                      Average Age of Population
AGE905                      Average Age of Adults >= 18
AGE906                      Average Age of Adults >= 25
AGE907                      Percent Population Under Age 18
CHIL1                       Percent Children Under Age 7
CHIL2                       Percent Children Age 7 - 13
CHIL3                       Percent Children Age 14-17
AGEC1                       Percent Adults Age18-24
AGEC2                       Percent Adults Age 25-34
AGEC3                       Percent Adults Age 35-44
AGEC4                       Percent Adults Age 45-54
AGEC5                       Percent Adults Age 55-64
AGEC6                       Percent Adults Age 65-74
AGEC7                       Percent Adults Age >= 75
CHILC1                      Percent Children Age <=2
CHILC2                      Percent Children Age 3-5
CHILC3                      Percent Children Age 6-11
CHILC4                      Percent Children Age 12-15
CHILC5                      Percent Children Age 16-18
HHAGE1                      Percent Households w/ Person 65+
HHAGE2                      Percent Households w/ Person 65+ Living Alone
HHAGE3                      Percent Households Headed by an Elderly Person Age 65+
HHN1                        Percent 1 Person Households
HHN2                        Percent 2 Person Households
HHN3                        Percent 3 or More Person Households
HHN4                        Percent 4 or More Person Households
HHN5                        Percent 5 or More Person Households
HHN6                        Percent 6 Person Households
MARR1                       Percent Married
MARR2                       Percent Separated or Divorced
MARR3                       Percent Widowed
MARR4                       Percent Never Married
HHP1                        Median Person Per Household
HHP2                        Average Person Per Household
DW1                         Percent Single Unit Structure
DW2                         Percent Detached Single Unit Structure
DW3                         Percent Duplex Structure
DW4                         Percent Multi (2+) Unit Structures
DW5                         Percent 3+ Unit Structures
DW6                         Percent Housing Units in 5+ Unit Structure
DW7                         Percent Group Quarters
DW8                         Percent Institutional Group Quarters
DW9                         Non-Institutional Group Quarters
HV1                         Median Home Value in hundreds
HV2                         Average Home Value in hundreds
HV3                         Median Contract Rent in hundreds
HV4                         Average Contract Rent in hundreds
HU1                         Percent Owner Occupied Housing Units
HU2                         Percent Renter Occupied Housing Units
HU3                         Percent Occupied Housing Units
HU4                         Percent Vacant Housing Units
HU5                         Percent Seasonal/Recreational Vacant Units
HHD1                        Percent Households w/ Related Children
HHD2                        Percent Households w/ Families
HHD3                        Percent Married Couple Families
HHD4                        Percent Married Couples w/ Related Children
HHD5                        Percent Persons in Family Household
HHD6                        Percent Persons in Non-Family Household
HHD7                        Percent Single Parent Households
HHD8                        Percent Male Householder w/ Child
HHD9                        Percent Female Householder w/ Child
HHD10                       Percent Single Male Householder
HHD11                       Percent Single Female Householder
HHD12                       Percent Households w/ Non-Family Living Arrangements
ETHC1                       Percent White < Age 15
ETHC2                       Percent White Age 15 - 59
ETHC3                       Percent White Age 60+
ETHC4                       Percent Black < Age 15
ETHC5                       Percent Black Age 15 - 59
ETHC6                       Percent Black Age 60+
HVP1                        Percent Home Value >= $200,000
HVP2                        Percent Home Value >= $150,000
HVP3                        Percent Home Value >= $100,000
HVP4                        Percent Home Value >= $75,000
HVP5                        Percent Home Value >= $50,000
HVP6                        Percent Home Value >= $300,000
HUR1                        $ 1 or 2 Room Housing Units
HUR2                        Percent >= 6 Room Housing Units
RHP1                        Median Number of Rooms per Housing Unit
RHP2                        Average Number of Rooms per Housing Unit
RHP3                        Median Number of Persons per Housing Unit
RHP4                        Average Number of Persons per Room
HUPA1                       Percent Housing Units w/ 2 thru 9 Units at the Address
HUPA2                       Percent Housing Units w/ >= 10 Units at the Address
HUPA3                       Percent Mobile Homes or Trailers
HUPA4                       Percent Renter Occupied Single Unit Structure
HUPA5                       Percent Renter Occupied, 2 - 4 Units
HUPA6                       Percent Renter Occupied, 5+ Units
HUPA7                       Percent Renter Occupied Mobile Homes or Trailers
RP1                         Percent Renters Paying >= $500 per Month
RP2                         Percent Renters Paying >= $400 per Month
RP3                         Percent Renters Paying >= $300 per Month
RP4                         Percent Renters Paying >= $200 per Month
MSA                         MSA Code
ADI                         ADI Code
DMA                         DMA Code
IC1                         Median Household Income in hundreds
IC2                         Median Family Income in hundreds
IC3                         Average Household Income in hundreds
IC4                         Average Family Income in hundreds
IC5                         Per Capita Income
IC6                         Percent Households w/ Income < $15,000
IC7                         Percent Households w/ Income $15,000 - $24,999
IC8                         Percent Households w/ Income $25,000 - $34,999
IC9                         Percent Households w/ Income $35,000 - $49,999
IC10                        Percent Households w/ Income $50,000 - $74,999
IC11                        Percent Households w/ Income $75,000 - $99,999
IC12                        Percent Households w/ Income $100,000 - $124,999
IC13                        Percent Households w/ Income $125,000 - $149,999
IC14                        Percent Households w/ Income >= $150,000
IC15                        Percent Families w/ Income < $15,000
IC16                        Percent Families w/ Income $15,000 - $24,999
IC17                        Percent Families w/ Income $25,000 - 34,999
IC18                        Percent Families w/ Income $35,000 - $49,999
IC19                        Percent Families w/ Income $50,000 - $74,999
IC20                        Percent Families w/ Income $75,000 - $99,999
IC21                        Percent Families w/ Income $100,000 - $124,999
IC22                        Percent Families w/ Income $125,000 - $149,999
IC23                        Percent Families w/ Income >= $150,000
HHAS1                       Percent Households on Social Security
HHAS2                       Percent Households on Public Assistance
HHAS3                       Percent Households w/ Interest, Rental or Dividend Income
HHAS4                       Percent Persons Below Poverty Level
MC1                         Percent Persons Move in Since 1985
MC2                         Percent Persons in Same House in 1985
MC3                         Percent Persons in Different State/Country in 1985
TPE1                        Percent Driving to Work Alone Car/Truck/Van
TPE2                        Percent Carpooling Car/Truck/Van)
TPE3                        Percent Using Public Transportation
TPE4                        Percent Using Bus/Trolley
TPE5                        Percent Using Railways
TPE6                        Percent Using Taxi/Ferry
TPE7                        Percent Using Motorcycles
TPE8                        Percent Using Other Transportation
TPE9                        Percent Working at Home/No Transportation
PEC1                        Percent Working Outside State of Residence
PEC2                        Percent Working Outside County of Residence in State
TPE10                       Median Travel Time to Work in minutes
TPE11                       Mean Travel Time to Work in minutes
TPE12                       Percent Traveling 60+ Minutes to Work
TPE13                       Percent Traveling 15 - 59 Minutes to Work
LFC1                        Percent Adults in Labor Force
LFC2                        Percent Adult Males in Labor Force
LFC3                        Percent Females in Labor Force
LFC4                        Percent Adult Males Employed
LFC5                        Percent Adult Females Employed
LFC6                        Percent Mothers Employed Married and Single
LFC7                        Percent 2 Parent Earner Families
LFC8                        Percent Single Mother w/ Child in Labor Force
LFC9                        Percent Single Father w/ Child in Labor Force
LFC10                       Percent Families w/ Child w/ no Workers
OCC1                        Percent Professional
OCC2                        Percent Managerial
OCC3                        Percent Technical
OCC4                        Percent Sales
OCC5                        Percent Clerical/Administrative Support
OCC6                        Percent Private Household Service Occ.
OCC7                        Percent Protective Service Occ.
OCC8                        Percent Other Service Occ.
OCC9                        Percent Farmers
OCC10                       Percent Craftsmen, Precision, Repair
OCC11                       Percent Operatives, Machine
OCC12                       Percent Transportation
OCC13                       Percent Laborers, Handlers, Helpers
EIC1                        Percent Employed in Agriculture
EIC2                        Percent Employed in Mining
EIC3                        Percent Employed in Construction
EIC4                        Percent Employed in Manufacturing
EIC5                        Percent Employed in Transportation
EIC6                        Percent Employed in Communications
EIC7                        Percent Employed in Wholesale Trade
EIC8                        Percent Employed in Retail Industry
EIC9                        Percent Employed in Finance, Insurance, Real Estate
EIC10                       Percent Employed in Business and Repair
EIC11                       Percent Employed in Personnal Services
EIC12                       Percent Employed in Entertainment and Recreation
EIC13                       Percent Employed in Health Services
EIC14                       Percent Employed in Educational Services
EIC15                       Percent Employed in Other Professional Services
EIC16                       Percent Employed in Public Administration
OEDC1                       Percent Employed by Local Government
OEDC2                       Percent Employed by State Government
OEDC3                       Percent Employed by Federal Government
OEDC4                       Percent Self Employed
OEDC5                       Percent Private Profit Wage or Salaried Worker
OEDC6                       Percent Private Non-Profit Wage or Salaried Worker
OEDC7                       Percent Unpaid Family Workers
EC1                         Median Years of School Completed by Adults 25+
EC2                         Percent Adults 25+ Grades 0-8
EC3                         Percent Adults 25+ w/ some High School
EC4                         Percent Adults 25+ Completed High School or Equivalency
EC5                         Percent Adults 25+ w/ some College
EC6                         Percent Adults 25+ w/ Associates Degree
EC7                         Percent Adults 25+ w/ Bachelors Degree
EC8                         Percent Adults 25+ Graduate Degree
SEC1                        Percent Persons Enrolled in Private Schools
SEC2                        Percent Persons Enrolled in Public Schools
SEC3                        Percent Persons Enrolled in Preschool
SEC4                        Percent Persons Enrolled in Elementary or High School
SEC5                        Percent Persons in College
AFC1                        Percent Adults in Active Military Service
AFC2                        Percent Males in Active Military Service
AFC3                        Percent Females in Active Military Service
AFC4                        Percent Adult Veterans Age 16+
AFC5                        Percent Male Veterans Age 16+
AFC6                        Percent Female Veterans Age 16+
VC1                         Percent Vietnam Veterans Age 16+
VC2                         Percent Korean Veterans Age 16+
VC3                         Percent WW2 Veterans Age 16+
VC4                         Percent Veterans Serving After May 1975 Only
ANC1                        Percent Dutch Ancestry
ANC2                        Percent English Ancestry
ANC3                        Percent French Ancestry
ANC4                        Percent German Ancestry
ANC5                        Percent Greek Ancestry
ANC6                        Percent Hungarian Ancestry
ANC7                        Percent Irish Ancestry
ANC8                        Percent Italian Ancestry
ANC9                        Percent Norwegian Ancestry
ANC10                       Percent Polish Ancestry
ANC11                       Percent Portuguese Ancestry
ANC12                       Percent Russian Ancestry
ANC13                       Percent Scottish Ancestry
ANC14                       Percent Swedish Ancestry
ANC15                       Percent Ukranian Ancestry
POBC1                       Percent Foreign Born
POBC2                       Percent Born in State of Residence
LSC1                        Percent English Only Speaking
LSC2                        Percent Spanish Speaking
LSC3                        Percent Asian Speaking
LSC4                        Percent Other Language Speaking
VOC1                        Percent Households w/ 1+ Vehicles
VOC2                        Percent Households w/ 2+ Vehicles
VOC3                        Percent Households w/ 3+ Vehicles
HC1                         Percent Median Length of Residence
HC2                         Percent Median Age of Occupied Dwellings in years
HC3                         Percent Owner Occupied Structures Built Since 1989
HC4                         Percent Owner Occupied Structures Built Since 1985
HC5                         Percent Owner Occupied Structures Built Since 1980
HC6                         Percent Owner Occupied Structures Built Since 1970
HC7                         Percent Owner Occupied Structures Built Since 1960
HC8                         Percent Owner Occupied Structures Built Prior to 1960
HC9                         Percent Owner Occupied Condominiums
HC10                        Percent Renter Occupied Condominiums
HC11                        Percent Occupied Housing Units Heated by Utility Gas
HC12                        Percent Occupied Housing Units Heated by Bottled, Tank or LP
HC13                        Percent Occupied Housing Units Heated by Electricity
HC14                        Percent Occupied Housing Units Heated by Fuel Oil
HC15                        Percent Occupied Housing Units Heated by Solar Energy
HC16                        Percent Occupied Housing Units Heated by Coal, Wood, Other
HC17                        Percent Housing Units w/ Public Water Source
HC18                        Percent Housing Units w/ Well Water Source
HC19                        Percent Housing Units w/ Public Sewer Source
HC20                        Percent Housing Units w/ Complete Plumbing Facilities
HC21                        Percent Housing Units w/ Telephones
MHUC1                       Median Homeowner Cost w/ Mortgage per Month dollars
MHUC2                       Median Homeowner Cost w/out Mortgage per Month dollars
AC1                         Percent Adults Age 55-59
AC2                         Percent Adults Age 60-64
                           
--------------------------  -------------------------------------------------
                      
                            The fields listed below are from the promotion history file.  

                            PROMOTION CODES: 
                            ----------------

                            The following lists the promotion codes and their 
                            respective field names (where XXXX refers to ADATE, RFA, 
                            RDATE and RAMNT.) 
                            
                            '97NK' ==> xxxx_2 (mailing was used to construct 
                                               the target fields)
                            '96NK' ==> xxxx_3
                            '96TK' ==> xxxx_4
                            '96SK' ==> xxxx_5
                            '96LL' ==> xxxx_6
                            '96G1' ==> xxxx_7
                            '96GK' ==> xxxx_8
                            '96CC' ==> xxxx_9
                            '96WL' ==> xxxx_10
                            '96X1' ==> xxxx_11
                            '96XK' ==> xxxx_12
                            '95FS' ==> xxxx_13
                            '95NK' ==> xxxx_14
                            '95TK' ==> xxxx_15
                            '95LL' ==> xxxx_16
                            '95G1' ==> xxxx_17
                            '95GK' ==> xxxx_18
                            '95CC' ==> xxxx_19
                            '95WL' ==> xxxx_20
                            '95X1' ==> xxxx_21
                            '95XK' ==> xxxx_22
                            '94FS' ==> xxxx_23
                            '94NK' ==> xxxx_24

                            1st 2 bytes of the code refers to the year of the 
                            mailing while 3rd and 4th bytes refer to the 
                            following promotion codes/types: 

                            LL mailings had labels only
                            WL mailings had labels only
                            CC mailings are calendars with stickers but do
                               not have labels
                            FS mailings are blank cards that fold into
                               thirds with labels
                            NK mailings are blank cards with labels
                            SK mailings are blank cards with labels
                            TK mailings have thank you printed on the
                               outside with labels
                            GK mailings are general greeting cards (an
                               assortment of birthday, sympathy, blank, & get
                               well) with labels
                            XK mailings are Christmas cards with labels
                            X1 mailings have labels and a notepad
                            G1 mailings have labels and a notepad
                            
                            This information could certainly be used to calculate 
                            several summary variables that count the number of 
                            occurrences of various types of promotions received 
                            in the most recent 12-36 months, etc. 

                            RFA (RECENCY/FREQUENCY/AMOUNT)
                            ------------------------------
 
                            The RFA (recency/frequency/amount) status of the 
                            donors (as of the promotion dates) is included in the 
                            RFA fields.
 
                            The (current) concatenated version is a nominal 
                            or symbolic field. The individual bytes could 
                            separately be used as fields and refer to the 
                            following: 

                            First Byte of code is concerned with RECENCY
                            based on Date of the last Gift

                            F=FIRST TIME DONOR Anyone who has made their
                              first donation in the last 6 months and has
                              made just one donation.

                            N=NEW DONOR Anyone who has made their first
                              donation in the last 12 months and is not a
                              First time donor.  This is everyone who made
                              their first donation 7-12 months ago, or
                              people who made their first donation between
                              0-6 months ago and have made 2 or more
                              donations.

                            A=ACTIVE DONOR Anyone who made their first
                              donation more than 12 months ago and has made
                              a donation in the last 12 months.

                            L=LAPSING DONOR A previous donor who made their
                              last donation between 13-24 months ago.

                            I=INACTIVE DONOR A previous donor who has not
                              made a donation in the last 24 months.  It is
                              people who made a donation 25+ months ago.

                            S=STAR DONOR STAR Donors are individuals who
                              have given to 3 consecutive card mailings.


                            Second Byte of code is concerned with FREQUENCY
                            based on the period of recency.  The period of
                            recency for all groups except L and I is the
                            last 12 months.  For L it is 13-24 months ago,
                            and for I it is 25-36 months ago.  There are
                            four valid frequency codes.

                            1=One gift in the period of recency 
                            2=Two gift in the period of recency 
                            3=Three gifts in the period of recency 
                            4=Four or more gifts in the period of recency

                            Third byte of the code is the Amount of the last
                            gift.

                            A=$0.01  -  $1.99
                            B=$2.00  -  $2.99
                            C=$3.00  -  $4.99
                            D=$5.00  -  $9.99
                            E=$10.00 - $14.99
                            F=$15.00 - $24.99
                            G=$25.00 and above


ADATE_2                     Date the 97NK promotion was mailed 
ADATE_3                     Date the 96NK promotion was mailed 
ADATE_4                     Date the 96TK promotion was mailed 
ADATE_5                     Date the 96SK promotion was mailed 
ADATE_6                     Date the 96LL promotion was mailed 
ADATE_7                     Date the 96G1 promotion was mailed 
ADATE_8                     Date the 96GK promotion was mailed 
ADATE_9                     Date the 96CC promotion was mailed 
ADATE_10                    Date the 96WL promotion was mailed
ADATE_11                    Date the 96X1 promotion was mailed
ADATE_12                    Date the 96XK promotion was mailed
ADATE_13                    Date the 95FS promotion was mailed
ADATE_14                    Date the 95NK promotion was mailed
ADATE_15                    Date the 95TK promotion was mailed
ADATE_16                    Date the 95LL promotion was mailed
ADATE_17                    Date the 95G1 promotion was mailed
ADATE_18                    Date the 95GK promotion was mailed
ADATE_19                    Date the 95CC promotion was mailed
ADATE_20                    Date the 95WL promotion was mailed
ADATE_21                    Date the 95X1 promotion was mailed
ADATE_22                    Date the 95XK promotion was mailed
ADATE_23                    Date the 94FS promotion was mailed
ADATE_24                    Date the 94NK promotion was mailed

RFA_2                       Donor's RFA status as of 97NK promotion date 
RFA_3                       Donor's RFA status as of 96NK promotion date  
RFA_4                       Donor's RFA status as of 96TK promotion date  
RFA_5                       Donor's RFA status as of 96SK promotion date  
RFA_6                       Donor's RFA status as of 96LL promotion date  
RFA_7                       Donor's RFA status as of 96G1 promotion date  
RFA_8                       Donor's RFA status as of 96GK promotion date  
RFA_9                       Donor's RFA status as of 96CC promotion date  
RFA_10                      Donor's RFA status as of 96WL promotion date 
RFA_11                      Donor's RFA status as of 96X1 promotion date 
RFA_12                      Donor's RFA status as of 96XK promotion date 
RFA_13                      Donor's RFA status as of 95FS promotion date 
RFA_14                      Donor's RFA status as of 95NK promotion date 
RFA_15                      Donor's RFA status as of 95TK promotion date 
RFA_16                      Donor's RFA status as of 95LL promotion date 
RFA_17                      Donor's RFA status as of 95G1 promotion date 
RFA_18                      Donor's RFA status as of 95GK promotion date 
RFA_19                      Donor's RFA status as of 95CC promotion date 
RFA_20                      Donor's RFA status as of 95WL promotion date 
RFA_21                      Donor's RFA status as of 95X1 promotion date 
RFA_22                      Donor's RFA status as of 95XK promotion date 
RFA_23                      Donor's RFA status as of 94FS promotion date 
RFA_24                      Donor's RFA status as of 94NK promotion date 

--------------------------  -------------------------------------------------
                            The following fields are summary variables from
                            the promotion history file. 

CARDPROM                    Lifetime number of card promotions received to 
                            date. Card promotions are promotion type FS, GK,
                            TK, SK, NK, XK, UF, UU.
MAXADATE                    Date of the most recent promotion received (in
                            YYMM, Year/Month format)
NUMPROM                     Lifetime number of promotions received to date
CARDPM12                    Number of card promotions received in the last
                            12 months (in terms of calendar months translates 
                            into 9603-9702) 
NUMPRM12                    Number of promotions received in the last 12
                            months (in terms of calendar months translates 
                            into 9603-9702)

--------------------------  -------------------------------------------------
                            The following fields are from the giving history 
                            file.

RDATE_3                     Date the gift was received for 96NK        
RDATE_4                     Date the gift was received for 96TK  
RDATE_5                     Date the gift was received for 96SK  
RDATE_6                     Date the gift was received for 96LL 
RDATE_7                     Date the gift was received for 96G1
RDATE_8                     Date the gift was received for 96GK
RDATE_9                     Date the gift was received for 96CC
RDATE_10                    Date the gift was received for 96WL
RDATE_11                    Date the gift was received for 96X1
RDATE_12                    Date the gift was received for 96XK
RDATE_13                    Date the gift was received for 95FS
RDATE_14                    Date the gift was received for 95NK
RDATE_15                    Date the gift was received for 95TK
RDATE_16                    Date the gift was received for 95LL
RDATE_17                    Date the gift was received for 95G1
RDATE_18                    Date the gift was received for 95GK
RDATE_19                    Date the gift was received for 95CC
RDATE_20                    Date the gift was received for 95WL
RDATE_21                    Date the gift was received for 95X1
RDATE_22                    Date the gift was received for 95XK
RDATE_23                    Date the gift was received for 94FS
RDATE_24                    Date the gift was received for 94NK
        
RAMNT_3                     Dollar amount of the gift for 96NK 
RAMNT_4                     Dollar amount of the gift for 96TK  
RAMNT_5                     Dollar amount of the gift for 96SK  
RAMNT_6                     Dollar amount of the gift for 96LL 
RAMNT_7                     Dollar amount of the gift for 96G1 
RAMNT_8                     Dollar amount of the gift for 96GK  
RAMNT_9                     Dollar amount of the gift for 96CC 
RAMNT_10                    Dollar amount of the gift for 96WL 
RAMNT_11                    Dollar amount of the gift for 96X1 
RAMNT_12                    Dollar amount of the gift for 96XK 
RAMNT_13                    Dollar amount of the gift for 95FS 
RAMNT_14                    Dollar amount of the gift for 95NK 
RAMNT_15                    Dollar amount of the gift for 95TK 
RAMNT_16                    Dollar amount of the gift for 95LL 
RAMNT_17                    Dollar amount of the gift for 95G1 
RAMNT_18                    Dollar amount of the gift for 95GK 
RAMNT_19                    Dollar amount of the gift for 95CC 
RAMNT_20                    Dollar amount of the gift for 95WL 
RAMNT_21                    Dollar amount of the gift for 95X1 
RAMNT_22                    Dollar amount of the gift for 95XK 
RAMNT_23                    Dollar amount of the gift for 94FS 
RAMNT_24                    Dollar amount of the gift for 94NK 

--------------------------  -------------------------------------------------
                            The following fields are summary variables from
                            the giving history file. 

RAMNTALL                    Dollar amount of lifetime gifts to date
NGIFTALL                    Number of lifetime gifts to date
CARDGIFT                    Number of lifetime gifts to card promotions to date 
MINRAMNT                    Dollar amount of smallest gift to date               
MINRDATE                    Date associated with the smallest gift to date
MAXRAMNT                    Dollar amount of largest gift to date              
MAXRDATE                    Date associated with the largest gift to date
LASTGIFT                    Dollar amount of most recent gift            
LASTDATE                    Date associated with the most recent gift               
FISTDATE                    Date of first gift 
NEXTDATE                    Date of second gift                    
TIMELAG                     Number of months between first and second gift
AVGGIFT                     Average dollar amount of gifts to date           

--------------------------  -------------------------------------------------
CONTROLN                    Control number (unique record identifier)

TARGET_B                    Target Variable: Binary Indicator for Response to 
                            97NK Mailing
TARGET_D                    Target Variable: Donation Amount (in $) associated 
                            with the Response to 97NK Mailing

HPHONE_D                    Indicator for presence of a published home 
                            phone number 

--------------------------  -------------------------------------------------
                            (See the section on RFA for the meaning of the 
                            codes)

RFA_2R                      Recency code for RFA_2                  
RFA_2F                      Frequency code for RFA_2                 
RFA_2A                      Donation Amount code for RFA_2          
MDMAUD_R                    Recency code for MDMAUD                 
MDMAUD_F                    Frequecy code for MDMAUD                
MDMAUD_A                    Donation Amount code for MDMAUD         

--------------------------  -------------------------------------------------
                           
CLUSTER2                    Classic Cluster Code (a nominal symbolic field)
GEOCODE2                    County Size Code 

======================================================================
EPSILON CONFIDENTIAL      EPSILON CONFIDENTIAL    EPSILON CONFIDENTIAL

    INFORMATION LISTED BELOW IS AVAILABLE UNDER THE TERMS OF THE  
                      CONFIDENTIALITY AGREEMENT                

EPSILON CONFIDENTIAL      EPSILON CONFIDENTIAL    EPSILON CONFIDENTIAL
======================================================================


```
