name: ma-thesis-fh
channels:
  - brittainhard
  - file:///data/anaconda/envs/py36/conda-bld
  - saravji
  - defaults
  - conda-forge
dependencies:
  - anaconda=custom=py36hbbc8b67_0
  - boruta=0.1.5
  - cartopy=0.17.0
  - category_encoders=2.0.0
  - conda
  - conda-build
  - cycler=0.10.0
  - geographiclib=1.49
  - glmnet=2.1.1
  - imbalanced-learn=0.4.3
  - jupyter=1.0.0
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_core
  - jupyter_nbextensions_configurator
  - knnimpute=0.1.0
  - missingno=0.4.1
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - notebook=5.7.8
  - numpy=1.16.3
  - pip
  - py-xgboost=0.80
  - python=3.6.7
  - python-dateutil
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - seaborn=0.9.0
  - pip:
    - fancyimpute==0.4.2
    - geopy==1.19.0
    - missingpy==0.2.0
    - mpmath==1.1.0

